
namespace management_store
{
    partial class UCNhanVien
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UCNhanVien));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.picImage = new System.Windows.Forms.PictureBox();
            this.txtLienHe = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtGioiTinh = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtHoTen = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCCCD = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtDiaChi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMaNV = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnChonHinhAnh = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnXoaSP = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnHuy = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLuuSP = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnThemSanPham = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.dgvNhanVien = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.label1 = new System.Windows.Forms.Label();
            this.pictureBox11 = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.picImage)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNhanVien)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox11)).BeginInit();
            this.SuspendLayout();
            // 
            // picImage
            // 
            this.picImage.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.picImage.Location = new System.Drawing.Point(845, 254);
            this.picImage.Name = "picImage";
            this.picImage.Size = new System.Drawing.Size(211, 252);
            this.picImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picImage.TabIndex = 34;
            this.picImage.TabStop = false;
            // 
            // txtLienHe
            // 
            this.txtLienHe.AcceptsReturn = false;
            this.txtLienHe.AcceptsTab = false;
            this.txtLienHe.AnimationSpeed = 200;
            this.txtLienHe.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtLienHe.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtLienHe.AutoSizeHeight = true;
            this.txtLienHe.BackColor = System.Drawing.Color.Transparent;
            this.txtLienHe.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtLienHe.BackgroundImage")));
            this.txtLienHe.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtLienHe.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtLienHe.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtLienHe.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtLienHe.BorderRadius = 1;
            this.txtLienHe.BorderThickness = 1;
            this.txtLienHe.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtLienHe.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLienHe.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtLienHe.DefaultText = "";
            this.txtLienHe.FillColor = System.Drawing.Color.White;
            this.txtLienHe.HideSelection = true;
            this.txtLienHe.IconLeft = null;
            this.txtLienHe.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLienHe.IconPadding = 10;
            this.txtLienHe.IconRight = null;
            this.txtLienHe.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLienHe.Lines = new string[0];
            this.txtLienHe.Location = new System.Drawing.Point(899, 133);
            this.txtLienHe.MaxLength = 32767;
            this.txtLienHe.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtLienHe.Modified = false;
            this.txtLienHe.Multiline = false;
            this.txtLienHe.Name = "txtLienHe";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLienHe.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtLienHe.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLienHe.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLienHe.OnIdleState = stateProperties4;
            this.txtLienHe.Padding = new System.Windows.Forms.Padding(3);
            this.txtLienHe.PasswordChar = '\0';
            this.txtLienHe.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtLienHe.PlaceholderText = "";
            this.txtLienHe.ReadOnly = false;
            this.txtLienHe.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtLienHe.SelectedText = "";
            this.txtLienHe.SelectionLength = 0;
            this.txtLienHe.SelectionStart = 0;
            this.txtLienHe.ShortcutsEnabled = true;
            this.txtLienHe.Size = new System.Drawing.Size(157, 39);
            this.txtLienHe.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtLienHe.TabIndex = 33;
            this.txtLienHe.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtLienHe.TextMarginBottom = 0;
            this.txtLienHe.TextMarginLeft = 3;
            this.txtLienHe.TextMarginTop = 1;
            this.txtLienHe.TextPlaceholder = "";
            this.txtLienHe.UseSystemPasswordChar = false;
            this.txtLienHe.WordWrap = true;
            // 
            // txtGioiTinh
            // 
            this.txtGioiTinh.AcceptsReturn = false;
            this.txtGioiTinh.AcceptsTab = false;
            this.txtGioiTinh.AnimationSpeed = 200;
            this.txtGioiTinh.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtGioiTinh.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtGioiTinh.AutoSizeHeight = true;
            this.txtGioiTinh.BackColor = System.Drawing.Color.Transparent;
            this.txtGioiTinh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtGioiTinh.BackgroundImage")));
            this.txtGioiTinh.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtGioiTinh.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtGioiTinh.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtGioiTinh.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtGioiTinh.BorderRadius = 1;
            this.txtGioiTinh.BorderThickness = 1;
            this.txtGioiTinh.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtGioiTinh.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGioiTinh.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtGioiTinh.DefaultText = "";
            this.txtGioiTinh.FillColor = System.Drawing.Color.White;
            this.txtGioiTinh.HideSelection = true;
            this.txtGioiTinh.IconLeft = null;
            this.txtGioiTinh.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGioiTinh.IconPadding = 10;
            this.txtGioiTinh.IconRight = null;
            this.txtGioiTinh.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGioiTinh.Lines = new string[0];
            this.txtGioiTinh.Location = new System.Drawing.Point(899, 76);
            this.txtGioiTinh.MaxLength = 32767;
            this.txtGioiTinh.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtGioiTinh.Modified = false;
            this.txtGioiTinh.Multiline = false;
            this.txtGioiTinh.Name = "txtGioiTinh";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGioiTinh.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtGioiTinh.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGioiTinh.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGioiTinh.OnIdleState = stateProperties8;
            this.txtGioiTinh.Padding = new System.Windows.Forms.Padding(3);
            this.txtGioiTinh.PasswordChar = '\0';
            this.txtGioiTinh.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtGioiTinh.PlaceholderText = "";
            this.txtGioiTinh.ReadOnly = false;
            this.txtGioiTinh.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtGioiTinh.SelectedText = "";
            this.txtGioiTinh.SelectionLength = 0;
            this.txtGioiTinh.SelectionStart = 0;
            this.txtGioiTinh.ShortcutsEnabled = true;
            this.txtGioiTinh.Size = new System.Drawing.Size(157, 39);
            this.txtGioiTinh.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtGioiTinh.TabIndex = 32;
            this.txtGioiTinh.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtGioiTinh.TextMarginBottom = 0;
            this.txtGioiTinh.TextMarginLeft = 3;
            this.txtGioiTinh.TextMarginTop = 1;
            this.txtGioiTinh.TextPlaceholder = "";
            this.txtGioiTinh.UseSystemPasswordChar = false;
            this.txtGioiTinh.WordWrap = true;
            // 
            // txtHoTen
            // 
            this.txtHoTen.AcceptsReturn = false;
            this.txtHoTen.AcceptsTab = false;
            this.txtHoTen.AnimationSpeed = 200;
            this.txtHoTen.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtHoTen.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtHoTen.AutoSizeHeight = true;
            this.txtHoTen.BackColor = System.Drawing.Color.Transparent;
            this.txtHoTen.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtHoTen.BackgroundImage")));
            this.txtHoTen.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtHoTen.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtHoTen.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtHoTen.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtHoTen.BorderRadius = 1;
            this.txtHoTen.BorderThickness = 1;
            this.txtHoTen.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtHoTen.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtHoTen.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtHoTen.DefaultText = "";
            this.txtHoTen.FillColor = System.Drawing.Color.White;
            this.txtHoTen.HideSelection = true;
            this.txtHoTen.IconLeft = null;
            this.txtHoTen.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtHoTen.IconPadding = 10;
            this.txtHoTen.IconRight = null;
            this.txtHoTen.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtHoTen.Lines = new string[0];
            this.txtHoTen.Location = new System.Drawing.Point(388, 76);
            this.txtHoTen.MaxLength = 32767;
            this.txtHoTen.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtHoTen.Modified = false;
            this.txtHoTen.Multiline = false;
            this.txtHoTen.Name = "txtHoTen";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtHoTen.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtHoTen.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtHoTen.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtHoTen.OnIdleState = stateProperties12;
            this.txtHoTen.Padding = new System.Windows.Forms.Padding(3);
            this.txtHoTen.PasswordChar = '\0';
            this.txtHoTen.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtHoTen.PlaceholderText = "";
            this.txtHoTen.ReadOnly = false;
            this.txtHoTen.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtHoTen.SelectedText = "";
            this.txtHoTen.SelectionLength = 0;
            this.txtHoTen.SelectionStart = 0;
            this.txtHoTen.ShortcutsEnabled = true;
            this.txtHoTen.Size = new System.Drawing.Size(402, 39);
            this.txtHoTen.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtHoTen.TabIndex = 31;
            this.txtHoTen.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtHoTen.TextMarginBottom = 0;
            this.txtHoTen.TextMarginLeft = 3;
            this.txtHoTen.TextMarginTop = 1;
            this.txtHoTen.TextPlaceholder = "";
            this.txtHoTen.UseSystemPasswordChar = false;
            this.txtHoTen.WordWrap = true;
            // 
            // txtCCCD
            // 
            this.txtCCCD.AcceptsReturn = false;
            this.txtCCCD.AcceptsTab = false;
            this.txtCCCD.AnimationSpeed = 200;
            this.txtCCCD.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCCCD.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCCCD.AutoSizeHeight = true;
            this.txtCCCD.BackColor = System.Drawing.Color.Transparent;
            this.txtCCCD.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCCCD.BackgroundImage")));
            this.txtCCCD.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCCCD.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCCCD.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCCCD.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCCCD.BorderRadius = 1;
            this.txtCCCD.BorderThickness = 1;
            this.txtCCCD.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCCCD.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCCCD.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCCCD.DefaultText = "";
            this.txtCCCD.FillColor = System.Drawing.Color.White;
            this.txtCCCD.HideSelection = true;
            this.txtCCCD.IconLeft = null;
            this.txtCCCD.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCCCD.IconPadding = 10;
            this.txtCCCD.IconRight = null;
            this.txtCCCD.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCCCD.Lines = new string[0];
            this.txtCCCD.Location = new System.Drawing.Point(121, 133);
            this.txtCCCD.MaxLength = 32767;
            this.txtCCCD.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCCCD.Modified = false;
            this.txtCCCD.Multiline = false;
            this.txtCCCD.Name = "txtCCCD";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCCCD.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCCCD.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCCCD.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCCCD.OnIdleState = stateProperties16;
            this.txtCCCD.Padding = new System.Windows.Forms.Padding(3);
            this.txtCCCD.PasswordChar = '\0';
            this.txtCCCD.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCCCD.PlaceholderText = "";
            this.txtCCCD.ReadOnly = false;
            this.txtCCCD.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCCCD.SelectedText = "";
            this.txtCCCD.SelectionLength = 0;
            this.txtCCCD.SelectionStart = 0;
            this.txtCCCD.ShortcutsEnabled = true;
            this.txtCCCD.Size = new System.Drawing.Size(151, 39);
            this.txtCCCD.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCCCD.TabIndex = 30;
            this.txtCCCD.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCCCD.TextMarginBottom = 0;
            this.txtCCCD.TextMarginLeft = 3;
            this.txtCCCD.TextMarginTop = 1;
            this.txtCCCD.TextPlaceholder = "";
            this.txtCCCD.UseSystemPasswordChar = false;
            this.txtCCCD.WordWrap = true;
            // 
            // txtDiaChi
            // 
            this.txtDiaChi.AcceptsReturn = false;
            this.txtDiaChi.AcceptsTab = false;
            this.txtDiaChi.AnimationSpeed = 200;
            this.txtDiaChi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDiaChi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDiaChi.AutoSizeHeight = true;
            this.txtDiaChi.BackColor = System.Drawing.Color.Transparent;
            this.txtDiaChi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDiaChi.BackgroundImage")));
            this.txtDiaChi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDiaChi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDiaChi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDiaChi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDiaChi.BorderRadius = 1;
            this.txtDiaChi.BorderThickness = 1;
            this.txtDiaChi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDiaChi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDiaChi.DefaultText = "";
            this.txtDiaChi.FillColor = System.Drawing.Color.White;
            this.txtDiaChi.HideSelection = true;
            this.txtDiaChi.IconLeft = null;
            this.txtDiaChi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.IconPadding = 10;
            this.txtDiaChi.IconRight = null;
            this.txtDiaChi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.Lines = new string[0];
            this.txtDiaChi.Location = new System.Drawing.Point(388, 133);
            this.txtDiaChi.MaxLength = 32767;
            this.txtDiaChi.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDiaChi.Modified = false;
            this.txtDiaChi.Multiline = false;
            this.txtDiaChi.Name = "txtDiaChi";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDiaChi.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnIdleState = stateProperties20;
            this.txtDiaChi.Padding = new System.Windows.Forms.Padding(3);
            this.txtDiaChi.PasswordChar = '\0';
            this.txtDiaChi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDiaChi.PlaceholderText = "";
            this.txtDiaChi.ReadOnly = false;
            this.txtDiaChi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDiaChi.SelectedText = "";
            this.txtDiaChi.SelectionLength = 0;
            this.txtDiaChi.SelectionStart = 0;
            this.txtDiaChi.ShortcutsEnabled = true;
            this.txtDiaChi.Size = new System.Drawing.Size(402, 39);
            this.txtDiaChi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDiaChi.TabIndex = 29;
            this.txtDiaChi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDiaChi.TextMarginBottom = 0;
            this.txtDiaChi.TextMarginLeft = 3;
            this.txtDiaChi.TextMarginTop = 1;
            this.txtDiaChi.TextPlaceholder = "";
            this.txtDiaChi.UseSystemPasswordChar = false;
            this.txtDiaChi.WordWrap = true;
            // 
            // txtMaNV
            // 
            this.txtMaNV.AcceptsReturn = false;
            this.txtMaNV.AcceptsTab = false;
            this.txtMaNV.AnimationSpeed = 200;
            this.txtMaNV.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMaNV.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMaNV.AutoSizeHeight = true;
            this.txtMaNV.BackColor = System.Drawing.Color.Transparent;
            this.txtMaNV.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMaNV.BackgroundImage")));
            this.txtMaNV.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMaNV.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMaNV.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMaNV.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMaNV.BorderRadius = 1;
            this.txtMaNV.BorderThickness = 1;
            this.txtMaNV.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMaNV.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaNV.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMaNV.DefaultText = "";
            this.txtMaNV.FillColor = System.Drawing.Color.White;
            this.txtMaNV.HideSelection = true;
            this.txtMaNV.IconLeft = null;
            this.txtMaNV.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaNV.IconPadding = 10;
            this.txtMaNV.IconRight = null;
            this.txtMaNV.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaNV.Lines = new string[0];
            this.txtMaNV.Location = new System.Drawing.Point(121, 76);
            this.txtMaNV.MaxLength = 32767;
            this.txtMaNV.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMaNV.Modified = false;
            this.txtMaNV.Multiline = false;
            this.txtMaNV.Name = "txtMaNV";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaNV.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMaNV.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaNV.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaNV.OnIdleState = stateProperties24;
            this.txtMaNV.Padding = new System.Windows.Forms.Padding(3);
            this.txtMaNV.PasswordChar = '\0';
            this.txtMaNV.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMaNV.PlaceholderText = "";
            this.txtMaNV.ReadOnly = true;
            this.txtMaNV.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMaNV.SelectedText = "";
            this.txtMaNV.SelectionLength = 0;
            this.txtMaNV.SelectionStart = 0;
            this.txtMaNV.ShortcutsEnabled = true;
            this.txtMaNV.Size = new System.Drawing.Size(151, 39);
            this.txtMaNV.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMaNV.TabIndex = 28;
            this.txtMaNV.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMaNV.TextMarginBottom = 0;
            this.txtMaNV.TextMarginLeft = 3;
            this.txtMaNV.TextMarginTop = 1;
            this.txtMaNV.TextPlaceholder = "";
            this.txtMaNV.UseSystemPasswordChar = false;
            this.txtMaNV.WordWrap = true;
            // 
            // btnChonHinhAnh
            // 
            this.btnChonHinhAnh.AllowAnimations = true;
            this.btnChonHinhAnh.AllowMouseEffects = true;
            this.btnChonHinhAnh.AllowToggling = false;
            this.btnChonHinhAnh.AnimationSpeed = 200;
            this.btnChonHinhAnh.AutoGenerateColors = false;
            this.btnChonHinhAnh.AutoRoundBorders = false;
            this.btnChonHinhAnh.AutoSizeLeftIcon = true;
            this.btnChonHinhAnh.AutoSizeRightIcon = true;
            this.btnChonHinhAnh.BackColor = System.Drawing.Color.Transparent;
            this.btnChonHinhAnh.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnChonHinhAnh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnChonHinhAnh.BackgroundImage")));
            this.btnChonHinhAnh.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChonHinhAnh.ButtonText = "Chọn ảnh";
            this.btnChonHinhAnh.ButtonTextMarginLeft = 0;
            this.btnChonHinhAnh.ColorContrastOnClick = 45;
            this.btnChonHinhAnh.ColorContrastOnHover = 45;
            this.btnChonHinhAnh.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnChonHinhAnh.CustomizableEdges = borderEdges1;
            this.btnChonHinhAnh.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnChonHinhAnh.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChonHinhAnh.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnChonHinhAnh.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnChonHinhAnh.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnChonHinhAnh.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnChonHinhAnh.ForeColor = System.Drawing.Color.White;
            this.btnChonHinhAnh.IconLeft = null;
            this.btnChonHinhAnh.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChonHinhAnh.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnChonHinhAnh.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnChonHinhAnh.IconMarginLeft = 11;
            this.btnChonHinhAnh.IconPadding = 10;
            this.btnChonHinhAnh.IconRight = null;
            this.btnChonHinhAnh.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChonHinhAnh.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnChonHinhAnh.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnChonHinhAnh.IconSize = 25;
            this.btnChonHinhAnh.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnChonHinhAnh.IdleBorderRadius = 0;
            this.btnChonHinhAnh.IdleBorderThickness = 0;
            this.btnChonHinhAnh.IdleFillColor = System.Drawing.Color.Empty;
            this.btnChonHinhAnh.IdleIconLeftImage = null;
            this.btnChonHinhAnh.IdleIconRightImage = null;
            this.btnChonHinhAnh.IndicateFocus = false;
            this.btnChonHinhAnh.Location = new System.Drawing.Point(845, 553);
            this.btnChonHinhAnh.Name = "btnChonHinhAnh";
            this.btnChonHinhAnh.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChonHinhAnh.OnDisabledState.BorderRadius = 1;
            this.btnChonHinhAnh.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChonHinhAnh.OnDisabledState.BorderThickness = 1;
            this.btnChonHinhAnh.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChonHinhAnh.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChonHinhAnh.OnDisabledState.IconLeftImage = null;
            this.btnChonHinhAnh.OnDisabledState.IconRightImage = null;
            this.btnChonHinhAnh.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnChonHinhAnh.onHoverState.BorderRadius = 1;
            this.btnChonHinhAnh.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChonHinhAnh.onHoverState.BorderThickness = 1;
            this.btnChonHinhAnh.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnChonHinhAnh.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnChonHinhAnh.onHoverState.IconLeftImage = null;
            this.btnChonHinhAnh.onHoverState.IconRightImage = null;
            this.btnChonHinhAnh.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnChonHinhAnh.OnIdleState.BorderRadius = 1;
            this.btnChonHinhAnh.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChonHinhAnh.OnIdleState.BorderThickness = 1;
            this.btnChonHinhAnh.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnChonHinhAnh.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnChonHinhAnh.OnIdleState.IconLeftImage = null;
            this.btnChonHinhAnh.OnIdleState.IconRightImage = null;
            this.btnChonHinhAnh.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChonHinhAnh.OnPressedState.BorderRadius = 1;
            this.btnChonHinhAnh.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChonHinhAnh.OnPressedState.BorderThickness = 1;
            this.btnChonHinhAnh.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChonHinhAnh.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnChonHinhAnh.OnPressedState.IconLeftImage = null;
            this.btnChonHinhAnh.OnPressedState.IconRightImage = null;
            this.btnChonHinhAnh.Size = new System.Drawing.Size(211, 39);
            this.btnChonHinhAnh.TabIndex = 26;
            this.btnChonHinhAnh.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnChonHinhAnh.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnChonHinhAnh.TextMarginLeft = 0;
            this.btnChonHinhAnh.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnChonHinhAnh.UseDefaultRadiusAndThickness = true;
            this.btnChonHinhAnh.Click += new System.EventHandler(this.btnChonHinhAnh_Click);
            // 
            // btnXoaSP
            // 
            this.btnXoaSP.AllowAnimations = true;
            this.btnXoaSP.AllowMouseEffects = true;
            this.btnXoaSP.AllowToggling = false;
            this.btnXoaSP.AnimationSpeed = 200;
            this.btnXoaSP.AutoGenerateColors = false;
            this.btnXoaSP.AutoRoundBorders = false;
            this.btnXoaSP.AutoSizeLeftIcon = true;
            this.btnXoaSP.AutoSizeRightIcon = true;
            this.btnXoaSP.BackColor = System.Drawing.Color.Transparent;
            this.btnXoaSP.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnXoaSP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXoaSP.BackgroundImage")));
            this.btnXoaSP.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaSP.ButtonText = "Xóa";
            this.btnXoaSP.ButtonTextMarginLeft = 0;
            this.btnXoaSP.ColorContrastOnClick = 45;
            this.btnXoaSP.ColorContrastOnHover = 45;
            this.btnXoaSP.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnXoaSP.CustomizableEdges = borderEdges2;
            this.btnXoaSP.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXoaSP.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoaSP.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnXoaSP.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnXoaSP.Enabled = false;
            this.btnXoaSP.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXoaSP.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnXoaSP.ForeColor = System.Drawing.Color.White;
            this.btnXoaSP.IconLeft = null;
            this.btnXoaSP.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnXoaSP.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoaSP.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnXoaSP.IconMarginLeft = 11;
            this.btnXoaSP.IconPadding = 10;
            this.btnXoaSP.IconRight = null;
            this.btnXoaSP.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnXoaSP.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoaSP.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnXoaSP.IconSize = 25;
            this.btnXoaSP.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnXoaSP.IdleBorderRadius = 0;
            this.btnXoaSP.IdleBorderThickness = 0;
            this.btnXoaSP.IdleFillColor = System.Drawing.Color.Empty;
            this.btnXoaSP.IdleIconLeftImage = null;
            this.btnXoaSP.IdleIconRightImage = null;
            this.btnXoaSP.IndicateFocus = false;
            this.btnXoaSP.Location = new System.Drawing.Point(640, 603);
            this.btnXoaSP.Name = "btnXoaSP";
            this.btnXoaSP.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoaSP.OnDisabledState.BorderRadius = 1;
            this.btnXoaSP.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaSP.OnDisabledState.BorderThickness = 1;
            this.btnXoaSP.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoaSP.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoaSP.OnDisabledState.IconLeftImage = null;
            this.btnXoaSP.OnDisabledState.IconRightImage = null;
            this.btnXoaSP.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnXoaSP.onHoverState.BorderRadius = 1;
            this.btnXoaSP.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaSP.onHoverState.BorderThickness = 1;
            this.btnXoaSP.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnXoaSP.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnXoaSP.onHoverState.IconLeftImage = null;
            this.btnXoaSP.onHoverState.IconRightImage = null;
            this.btnXoaSP.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnXoaSP.OnIdleState.BorderRadius = 1;
            this.btnXoaSP.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaSP.OnIdleState.BorderThickness = 1;
            this.btnXoaSP.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnXoaSP.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnXoaSP.OnIdleState.IconLeftImage = null;
            this.btnXoaSP.OnIdleState.IconRightImage = null;
            this.btnXoaSP.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXoaSP.OnPressedState.BorderRadius = 1;
            this.btnXoaSP.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaSP.OnPressedState.BorderThickness = 1;
            this.btnXoaSP.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXoaSP.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnXoaSP.OnPressedState.IconLeftImage = null;
            this.btnXoaSP.OnPressedState.IconRightImage = null;
            this.btnXoaSP.Size = new System.Drawing.Size(150, 39);
            this.btnXoaSP.TabIndex = 25;
            this.btnXoaSP.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXoaSP.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnXoaSP.TextMarginLeft = 0;
            this.btnXoaSP.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnXoaSP.UseDefaultRadiusAndThickness = true;
            this.btnXoaSP.Click += new System.EventHandler(this.btnXoaSP_Click);
            // 
            // btnHuy
            // 
            this.btnHuy.AllowAnimations = true;
            this.btnHuy.AllowMouseEffects = true;
            this.btnHuy.AllowToggling = false;
            this.btnHuy.AnimationSpeed = 200;
            this.btnHuy.AutoGenerateColors = false;
            this.btnHuy.AutoRoundBorders = false;
            this.btnHuy.AutoSizeLeftIcon = true;
            this.btnHuy.AutoSizeRightIcon = true;
            this.btnHuy.BackColor = System.Drawing.Color.Transparent;
            this.btnHuy.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnHuy.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHuy.BackgroundImage")));
            this.btnHuy.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHuy.ButtonText = "Hủy";
            this.btnHuy.ButtonTextMarginLeft = 0;
            this.btnHuy.ColorContrastOnClick = 45;
            this.btnHuy.ColorContrastOnHover = 45;
            this.btnHuy.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnHuy.CustomizableEdges = borderEdges3;
            this.btnHuy.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHuy.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHuy.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnHuy.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnHuy.Enabled = false;
            this.btnHuy.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHuy.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnHuy.ForeColor = System.Drawing.Color.White;
            this.btnHuy.IconLeft = null;
            this.btnHuy.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHuy.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnHuy.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHuy.IconMarginLeft = 11;
            this.btnHuy.IconPadding = 10;
            this.btnHuy.IconRight = null;
            this.btnHuy.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHuy.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnHuy.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHuy.IconSize = 25;
            this.btnHuy.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnHuy.IdleBorderRadius = 0;
            this.btnHuy.IdleBorderThickness = 0;
            this.btnHuy.IdleFillColor = System.Drawing.Color.Empty;
            this.btnHuy.IdleIconLeftImage = null;
            this.btnHuy.IdleIconRightImage = null;
            this.btnHuy.IndicateFocus = false;
            this.btnHuy.Location = new System.Drawing.Point(437, 603);
            this.btnHuy.Name = "btnHuy";
            this.btnHuy.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHuy.OnDisabledState.BorderRadius = 1;
            this.btnHuy.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHuy.OnDisabledState.BorderThickness = 1;
            this.btnHuy.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHuy.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHuy.OnDisabledState.IconLeftImage = null;
            this.btnHuy.OnDisabledState.IconRightImage = null;
            this.btnHuy.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnHuy.onHoverState.BorderRadius = 1;
            this.btnHuy.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHuy.onHoverState.BorderThickness = 1;
            this.btnHuy.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnHuy.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnHuy.onHoverState.IconLeftImage = null;
            this.btnHuy.onHoverState.IconRightImage = null;
            this.btnHuy.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnHuy.OnIdleState.BorderRadius = 1;
            this.btnHuy.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHuy.OnIdleState.BorderThickness = 1;
            this.btnHuy.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnHuy.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnHuy.OnIdleState.IconLeftImage = null;
            this.btnHuy.OnIdleState.IconRightImage = null;
            this.btnHuy.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnHuy.OnPressedState.BorderRadius = 1;
            this.btnHuy.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHuy.OnPressedState.BorderThickness = 1;
            this.btnHuy.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnHuy.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnHuy.OnPressedState.IconLeftImage = null;
            this.btnHuy.OnPressedState.IconRightImage = null;
            this.btnHuy.Size = new System.Drawing.Size(150, 39);
            this.btnHuy.TabIndex = 24;
            this.btnHuy.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHuy.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHuy.TextMarginLeft = 0;
            this.btnHuy.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnHuy.UseDefaultRadiusAndThickness = true;
            this.btnHuy.Click += new System.EventHandler(this.btnHuy_Click);
            // 
            // btnLuuSP
            // 
            this.btnLuuSP.AllowAnimations = true;
            this.btnLuuSP.AllowMouseEffects = true;
            this.btnLuuSP.AllowToggling = false;
            this.btnLuuSP.AnimationSpeed = 200;
            this.btnLuuSP.AutoGenerateColors = false;
            this.btnLuuSP.AutoRoundBorders = false;
            this.btnLuuSP.AutoSizeLeftIcon = true;
            this.btnLuuSP.AutoSizeRightIcon = true;
            this.btnLuuSP.BackColor = System.Drawing.Color.Transparent;
            this.btnLuuSP.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnLuuSP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLuuSP.BackgroundImage")));
            this.btnLuuSP.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuuSP.ButtonText = "Lưu";
            this.btnLuuSP.ButtonTextMarginLeft = 0;
            this.btnLuuSP.ColorContrastOnClick = 45;
            this.btnLuuSP.ColorContrastOnHover = 45;
            this.btnLuuSP.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnLuuSP.CustomizableEdges = borderEdges4;
            this.btnLuuSP.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLuuSP.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLuuSP.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnLuuSP.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnLuuSP.Enabled = false;
            this.btnLuuSP.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLuuSP.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLuuSP.ForeColor = System.Drawing.Color.White;
            this.btnLuuSP.IconLeft = null;
            this.btnLuuSP.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLuuSP.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLuuSP.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLuuSP.IconMarginLeft = 11;
            this.btnLuuSP.IconPadding = 10;
            this.btnLuuSP.IconRight = null;
            this.btnLuuSP.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLuuSP.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLuuSP.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLuuSP.IconSize = 25;
            this.btnLuuSP.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnLuuSP.IdleBorderRadius = 0;
            this.btnLuuSP.IdleBorderThickness = 0;
            this.btnLuuSP.IdleFillColor = System.Drawing.Color.Empty;
            this.btnLuuSP.IdleIconLeftImage = null;
            this.btnLuuSP.IdleIconRightImage = null;
            this.btnLuuSP.IndicateFocus = false;
            this.btnLuuSP.Location = new System.Drawing.Point(238, 603);
            this.btnLuuSP.Name = "btnLuuSP";
            this.btnLuuSP.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLuuSP.OnDisabledState.BorderRadius = 1;
            this.btnLuuSP.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuuSP.OnDisabledState.BorderThickness = 1;
            this.btnLuuSP.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLuuSP.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLuuSP.OnDisabledState.IconLeftImage = null;
            this.btnLuuSP.OnDisabledState.IconRightImage = null;
            this.btnLuuSP.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnLuuSP.onHoverState.BorderRadius = 1;
            this.btnLuuSP.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuuSP.onHoverState.BorderThickness = 1;
            this.btnLuuSP.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnLuuSP.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLuuSP.onHoverState.IconLeftImage = null;
            this.btnLuuSP.onHoverState.IconRightImage = null;
            this.btnLuuSP.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnLuuSP.OnIdleState.BorderRadius = 1;
            this.btnLuuSP.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuuSP.OnIdleState.BorderThickness = 1;
            this.btnLuuSP.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnLuuSP.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLuuSP.OnIdleState.IconLeftImage = null;
            this.btnLuuSP.OnIdleState.IconRightImage = null;
            this.btnLuuSP.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLuuSP.OnPressedState.BorderRadius = 1;
            this.btnLuuSP.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuuSP.OnPressedState.BorderThickness = 1;
            this.btnLuuSP.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLuuSP.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLuuSP.OnPressedState.IconLeftImage = null;
            this.btnLuuSP.OnPressedState.IconRightImage = null;
            this.btnLuuSP.Size = new System.Drawing.Size(150, 39);
            this.btnLuuSP.TabIndex = 27;
            this.btnLuuSP.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLuuSP.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLuuSP.TextMarginLeft = 0;
            this.btnLuuSP.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLuuSP.UseDefaultRadiusAndThickness = true;
            this.btnLuuSP.Click += new System.EventHandler(this.btnLuuSP_Click);
            // 
            // btnThemSanPham
            // 
            this.btnThemSanPham.AllowAnimations = true;
            this.btnThemSanPham.AllowMouseEffects = true;
            this.btnThemSanPham.AllowToggling = false;
            this.btnThemSanPham.AnimationSpeed = 200;
            this.btnThemSanPham.AutoGenerateColors = false;
            this.btnThemSanPham.AutoRoundBorders = false;
            this.btnThemSanPham.AutoSizeLeftIcon = true;
            this.btnThemSanPham.AutoSizeRightIcon = true;
            this.btnThemSanPham.BackColor = System.Drawing.Color.Transparent;
            this.btnThemSanPham.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnThemSanPham.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThemSanPham.BackgroundImage")));
            this.btnThemSanPham.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThemSanPham.ButtonText = "Thêm";
            this.btnThemSanPham.ButtonTextMarginLeft = 0;
            this.btnThemSanPham.ColorContrastOnClick = 45;
            this.btnThemSanPham.ColorContrastOnHover = 45;
            this.btnThemSanPham.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnThemSanPham.CustomizableEdges = borderEdges5;
            this.btnThemSanPham.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThemSanPham.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThemSanPham.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnThemSanPham.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnThemSanPham.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThemSanPham.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnThemSanPham.ForeColor = System.Drawing.Color.White;
            this.btnThemSanPham.IconLeft = null;
            this.btnThemSanPham.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThemSanPham.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnThemSanPham.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnThemSanPham.IconMarginLeft = 11;
            this.btnThemSanPham.IconPadding = 10;
            this.btnThemSanPham.IconRight = null;
            this.btnThemSanPham.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThemSanPham.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnThemSanPham.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThemSanPham.IconSize = 25;
            this.btnThemSanPham.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnThemSanPham.IdleBorderRadius = 0;
            this.btnThemSanPham.IdleBorderThickness = 0;
            this.btnThemSanPham.IdleFillColor = System.Drawing.Color.Empty;
            this.btnThemSanPham.IdleIconLeftImage = null;
            this.btnThemSanPham.IdleIconRightImage = null;
            this.btnThemSanPham.IndicateFocus = false;
            this.btnThemSanPham.Location = new System.Drawing.Point(37, 603);
            this.btnThemSanPham.Name = "btnThemSanPham";
            this.btnThemSanPham.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThemSanPham.OnDisabledState.BorderRadius = 1;
            this.btnThemSanPham.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThemSanPham.OnDisabledState.BorderThickness = 1;
            this.btnThemSanPham.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThemSanPham.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThemSanPham.OnDisabledState.IconLeftImage = null;
            this.btnThemSanPham.OnDisabledState.IconRightImage = null;
            this.btnThemSanPham.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnThemSanPham.onHoverState.BorderRadius = 1;
            this.btnThemSanPham.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThemSanPham.onHoverState.BorderThickness = 1;
            this.btnThemSanPham.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnThemSanPham.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnThemSanPham.onHoverState.IconLeftImage = null;
            this.btnThemSanPham.onHoverState.IconRightImage = null;
            this.btnThemSanPham.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnThemSanPham.OnIdleState.BorderRadius = 1;
            this.btnThemSanPham.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThemSanPham.OnIdleState.BorderThickness = 1;
            this.btnThemSanPham.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnThemSanPham.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnThemSanPham.OnIdleState.IconLeftImage = null;
            this.btnThemSanPham.OnIdleState.IconRightImage = null;
            this.btnThemSanPham.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThemSanPham.OnPressedState.BorderRadius = 1;
            this.btnThemSanPham.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThemSanPham.OnPressedState.BorderThickness = 1;
            this.btnThemSanPham.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThemSanPham.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnThemSanPham.OnPressedState.IconLeftImage = null;
            this.btnThemSanPham.OnPressedState.IconRightImage = null;
            this.btnThemSanPham.Size = new System.Drawing.Size(150, 39);
            this.btnThemSanPham.TabIndex = 23;
            this.btnThemSanPham.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThemSanPham.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThemSanPham.TextMarginLeft = 0;
            this.btnThemSanPham.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnThemSanPham.UseDefaultRadiusAndThickness = true;
            this.btnThemSanPham.Click += new System.EventHandler(this.btnThemSanPham_Click);
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(308, 140);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(59, 23);
            this.bunifuLabel6.TabIndex = 22;
            this.bunifuLabel6.Text = "Địa chỉ : ";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.Location = new System.Drawing.Point(39, 142);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(50, 23);
            this.bunifuLabel5.TabIndex = 20;
            this.bunifuLabel5.Text = "CCCD : ";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.Location = new System.Drawing.Point(821, 142);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(62, 23);
            this.bunifuLabel4.TabIndex = 18;
            this.bunifuLabel4.Text = "Liên hệ :";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(821, 83);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(72, 23);
            this.bunifuLabel3.TabIndex = 17;
            this.bunifuLabel3.Text = "Giới tính : ";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.Location = new System.Drawing.Point(306, 85);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(59, 23);
            this.bunifuLabel2.TabIndex = 16;
            this.bunifuLabel2.Text = "Họ tên : ";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(41, 82);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(57, 23);
            this.bunifuLabel1.TabIndex = 15;
            this.bunifuLabel1.Text = "Mã NV : ";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // dgvNhanVien
            // 
            this.dgvNhanVien.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dgvNhanVien.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvNhanVien.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvNhanVien.BackgroundColor = System.Drawing.Color.LightSeaGreen;
            this.dgvNhanVien.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvNhanVien.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvNhanVien.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvNhanVien.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvNhanVien.ColumnHeadersHeight = 40;
            this.dgvNhanVien.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgvNhanVien.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvNhanVien.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvNhanVien.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvNhanVien.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvNhanVien.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgvNhanVien.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvNhanVien.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgvNhanVien.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvNhanVien.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvNhanVien.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgvNhanVien.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvNhanVien.CurrentTheme.Name = null;
            this.dgvNhanVien.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgvNhanVien.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvNhanVien.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvNhanVien.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvNhanVien.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvNhanVien.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvNhanVien.EnableHeadersVisualStyles = false;
            this.dgvNhanVien.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvNhanVien.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgvNhanVien.HeaderForeColor = System.Drawing.Color.White;
            this.dgvNhanVien.Location = new System.Drawing.Point(37, 185);
            this.dgvNhanVien.Name = "dgvNhanVien";
            this.dgvNhanVien.RowHeadersVisible = false;
            this.dgvNhanVien.RowTemplate.Height = 40;
            this.dgvNhanVien.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvNhanVien.Size = new System.Drawing.Size(753, 407);
            this.dgvNhanVien.TabIndex = 14;
            this.dgvNhanVien.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Open Sans", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label1.Location = new System.Drawing.Point(513, 12);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(172, 39);
            this.label1.TabIndex = 12;
            this.label1.Text = "NHÂN VIÊN";
            // 
            // pictureBox11
            // 
            this.pictureBox11.Image = global::management_store.Properties.Resources.icons8_group_64;
            this.pictureBox11.Location = new System.Drawing.Point(457, 12);
            this.pictureBox11.Name = "pictureBox11";
            this.pictureBox11.Size = new System.Drawing.Size(50, 41);
            this.pictureBox11.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox11.TabIndex = 35;
            this.pictureBox11.TabStop = false;
            // 
            // UCNhanVien
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.AutoSize = true;
            this.Controls.Add(this.pictureBox11);
            this.Controls.Add(this.picImage);
            this.Controls.Add(this.txtLienHe);
            this.Controls.Add(this.txtGioiTinh);
            this.Controls.Add(this.txtHoTen);
            this.Controls.Add(this.txtCCCD);
            this.Controls.Add(this.txtDiaChi);
            this.Controls.Add(this.txtMaNV);
            this.Controls.Add(this.btnChonHinhAnh);
            this.Controls.Add(this.btnXoaSP);
            this.Controls.Add(this.btnHuy);
            this.Controls.Add(this.btnLuuSP);
            this.Controls.Add(this.btnThemSanPham);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.dgvNhanVien);
            this.Controls.Add(this.label1);
            this.Margin = new System.Windows.Forms.Padding(0);
            this.MaximumSize = new System.Drawing.Size(1100, 655);
            this.MinimumSize = new System.Drawing.Size(1100, 655);
            this.Name = "UCNhanVien";
            this.Size = new System.Drawing.Size(1100, 655);
            ((System.ComponentModel.ISupportInitialize)(this.picImage)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNhanVien)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox11)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PictureBox picImage;
        private Bunifu.UI.WinForms.BunifuTextBox txtLienHe;
        private Bunifu.UI.WinForms.BunifuTextBox txtGioiTinh;
        private Bunifu.UI.WinForms.BunifuTextBox txtHoTen;
        private Bunifu.UI.WinForms.BunifuTextBox txtCCCD;
        private Bunifu.UI.WinForms.BunifuTextBox txtDiaChi;
        private Bunifu.UI.WinForms.BunifuTextBox txtMaNV;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnChonHinhAnh;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXoaSP;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHuy;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLuuSP;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThemSanPham;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvNhanVien;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.PictureBox pictureBox11;
    }
}
