
namespace management_store
{
    partial class frmDoiThongTinCaNhan
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmDoiThongTinCaNhan));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.picImage = new System.Windows.Forms.PictureBox();
            this.txtLienHe = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtGioiTinh = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtHoTen = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCCCD = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtDiaChi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMaNV = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnChonHinhAnh = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.pnlInfor = new System.Windows.Forms.Panel();
            this.btnHuy = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLuu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.picImage)).BeginInit();
            this.pnlInfor.SuspendLayout();
            this.SuspendLayout();
            // 
            // picImage
            // 
            this.picImage.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.picImage.Image = ((System.Drawing.Image)(resources.GetObject("picImage.Image")));
            this.picImage.Location = new System.Drawing.Point(753, 20);
            this.picImage.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.picImage.Name = "picImage";
            this.picImage.Size = new System.Drawing.Size(281, 310);
            this.picImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picImage.TabIndex = 48;
            this.picImage.TabStop = false;
            // 
            // txtLienHe
            // 
            this.txtLienHe.AcceptsReturn = false;
            this.txtLienHe.AcceptsTab = false;
            this.txtLienHe.AnimationSpeed = 200;
            this.txtLienHe.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtLienHe.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtLienHe.AutoSizeHeight = true;
            this.txtLienHe.BackColor = System.Drawing.Color.Transparent;
            this.txtLienHe.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtLienHe.BackgroundImage")));
            this.txtLienHe.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtLienHe.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtLienHe.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtLienHe.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtLienHe.BorderRadius = 1;
            this.txtLienHe.BorderThickness = 1;
            this.txtLienHe.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtLienHe.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLienHe.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtLienHe.DefaultText = "";
            this.txtLienHe.FillColor = System.Drawing.Color.White;
            this.txtLienHe.HideSelection = true;
            this.txtLienHe.IconLeft = null;
            this.txtLienHe.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLienHe.IconPadding = 10;
            this.txtLienHe.IconRight = null;
            this.txtLienHe.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLienHe.Lines = new string[0];
            this.txtLienHe.Location = new System.Drawing.Point(148, 350);
            this.txtLienHe.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtLienHe.MaxLength = 32767;
            this.txtLienHe.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtLienHe.Modified = false;
            this.txtLienHe.Multiline = false;
            this.txtLienHe.Name = "txtLienHe";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLienHe.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtLienHe.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLienHe.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLienHe.OnIdleState = stateProperties4;
            this.txtLienHe.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtLienHe.PasswordChar = '\0';
            this.txtLienHe.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtLienHe.PlaceholderText = "";
            this.txtLienHe.ReadOnly = false;
            this.txtLienHe.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtLienHe.SelectedText = "";
            this.txtLienHe.SelectionLength = 0;
            this.txtLienHe.SelectionStart = 0;
            this.txtLienHe.ShortcutsEnabled = true;
            this.txtLienHe.Size = new System.Drawing.Size(555, 54);
            this.txtLienHe.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtLienHe.TabIndex = 47;
            this.txtLienHe.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtLienHe.TextMarginBottom = 0;
            this.txtLienHe.TextMarginLeft = 3;
            this.txtLienHe.TextMarginTop = 1;
            this.txtLienHe.TextPlaceholder = "";
            this.txtLienHe.UseSystemPasswordChar = false;
            this.txtLienHe.WordWrap = true;
            // 
            // txtGioiTinh
            // 
            this.txtGioiTinh.AcceptsReturn = false;
            this.txtGioiTinh.AcceptsTab = false;
            this.txtGioiTinh.AnimationSpeed = 200;
            this.txtGioiTinh.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtGioiTinh.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtGioiTinh.AutoSizeHeight = true;
            this.txtGioiTinh.BackColor = System.Drawing.Color.Transparent;
            this.txtGioiTinh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtGioiTinh.BackgroundImage")));
            this.txtGioiTinh.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtGioiTinh.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtGioiTinh.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtGioiTinh.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtGioiTinh.BorderRadius = 1;
            this.txtGioiTinh.BorderThickness = 1;
            this.txtGioiTinh.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtGioiTinh.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGioiTinh.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtGioiTinh.DefaultText = "";
            this.txtGioiTinh.FillColor = System.Drawing.Color.White;
            this.txtGioiTinh.HideSelection = true;
            this.txtGioiTinh.IconLeft = null;
            this.txtGioiTinh.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGioiTinh.IconPadding = 10;
            this.txtGioiTinh.IconRight = null;
            this.txtGioiTinh.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGioiTinh.Lines = new string[0];
            this.txtGioiTinh.Location = new System.Drawing.Point(148, 165);
            this.txtGioiTinh.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtGioiTinh.MaxLength = 32767;
            this.txtGioiTinh.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtGioiTinh.Modified = false;
            this.txtGioiTinh.Multiline = false;
            this.txtGioiTinh.Name = "txtGioiTinh";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGioiTinh.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtGioiTinh.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGioiTinh.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGioiTinh.OnIdleState = stateProperties8;
            this.txtGioiTinh.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtGioiTinh.PasswordChar = '\0';
            this.txtGioiTinh.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtGioiTinh.PlaceholderText = "";
            this.txtGioiTinh.ReadOnly = false;
            this.txtGioiTinh.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtGioiTinh.SelectedText = "";
            this.txtGioiTinh.SelectionLength = 0;
            this.txtGioiTinh.SelectionStart = 0;
            this.txtGioiTinh.ShortcutsEnabled = true;
            this.txtGioiTinh.Size = new System.Drawing.Size(555, 54);
            this.txtGioiTinh.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtGioiTinh.TabIndex = 46;
            this.txtGioiTinh.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtGioiTinh.TextMarginBottom = 0;
            this.txtGioiTinh.TextMarginLeft = 3;
            this.txtGioiTinh.TextMarginTop = 1;
            this.txtGioiTinh.TextPlaceholder = "";
            this.txtGioiTinh.UseSystemPasswordChar = false;
            this.txtGioiTinh.WordWrap = true;
            // 
            // txtHoTen
            // 
            this.txtHoTen.AcceptsReturn = false;
            this.txtHoTen.AcceptsTab = false;
            this.txtHoTen.AnimationSpeed = 200;
            this.txtHoTen.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtHoTen.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtHoTen.AutoSizeHeight = true;
            this.txtHoTen.BackColor = System.Drawing.Color.Transparent;
            this.txtHoTen.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtHoTen.BackgroundImage")));
            this.txtHoTen.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtHoTen.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtHoTen.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtHoTen.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtHoTen.BorderRadius = 1;
            this.txtHoTen.BorderThickness = 1;
            this.txtHoTen.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtHoTen.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtHoTen.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtHoTen.DefaultText = "";
            this.txtHoTen.FillColor = System.Drawing.Color.White;
            this.txtHoTen.HideSelection = true;
            this.txtHoTen.IconLeft = null;
            this.txtHoTen.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtHoTen.IconPadding = 10;
            this.txtHoTen.IconRight = null;
            this.txtHoTen.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtHoTen.Lines = new string[0];
            this.txtHoTen.Location = new System.Drawing.Point(148, 103);
            this.txtHoTen.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtHoTen.MaxLength = 32767;
            this.txtHoTen.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtHoTen.Modified = false;
            this.txtHoTen.Multiline = false;
            this.txtHoTen.Name = "txtHoTen";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtHoTen.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtHoTen.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtHoTen.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtHoTen.OnIdleState = stateProperties12;
            this.txtHoTen.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtHoTen.PasswordChar = '\0';
            this.txtHoTen.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtHoTen.PlaceholderText = "";
            this.txtHoTen.ReadOnly = false;
            this.txtHoTen.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtHoTen.SelectedText = "";
            this.txtHoTen.SelectionLength = 0;
            this.txtHoTen.SelectionStart = 0;
            this.txtHoTen.ShortcutsEnabled = true;
            this.txtHoTen.Size = new System.Drawing.Size(555, 54);
            this.txtHoTen.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtHoTen.TabIndex = 45;
            this.txtHoTen.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtHoTen.TextMarginBottom = 0;
            this.txtHoTen.TextMarginLeft = 3;
            this.txtHoTen.TextMarginTop = 1;
            this.txtHoTen.TextPlaceholder = "";
            this.txtHoTen.UseSystemPasswordChar = false;
            this.txtHoTen.WordWrap = true;
            // 
            // txtCCCD
            // 
            this.txtCCCD.AcceptsReturn = false;
            this.txtCCCD.AcceptsTab = false;
            this.txtCCCD.AnimationSpeed = 200;
            this.txtCCCD.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCCCD.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCCCD.AutoSizeHeight = true;
            this.txtCCCD.BackColor = System.Drawing.Color.Transparent;
            this.txtCCCD.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCCCD.BackgroundImage")));
            this.txtCCCD.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCCCD.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCCCD.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCCCD.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCCCD.BorderRadius = 1;
            this.txtCCCD.BorderThickness = 1;
            this.txtCCCD.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCCCD.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCCCD.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCCCD.DefaultText = "";
            this.txtCCCD.FillColor = System.Drawing.Color.White;
            this.txtCCCD.HideSelection = true;
            this.txtCCCD.IconLeft = null;
            this.txtCCCD.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCCCD.IconPadding = 10;
            this.txtCCCD.IconRight = null;
            this.txtCCCD.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCCCD.Lines = new string[0];
            this.txtCCCD.Location = new System.Drawing.Point(148, 288);
            this.txtCCCD.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtCCCD.MaxLength = 32767;
            this.txtCCCD.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCCCD.Modified = false;
            this.txtCCCD.Multiline = false;
            this.txtCCCD.Name = "txtCCCD";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCCCD.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCCCD.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCCCD.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCCCD.OnIdleState = stateProperties16;
            this.txtCCCD.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtCCCD.PasswordChar = '\0';
            this.txtCCCD.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCCCD.PlaceholderText = "";
            this.txtCCCD.ReadOnly = false;
            this.txtCCCD.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCCCD.SelectedText = "";
            this.txtCCCD.SelectionLength = 0;
            this.txtCCCD.SelectionStart = 0;
            this.txtCCCD.ShortcutsEnabled = true;
            this.txtCCCD.Size = new System.Drawing.Size(555, 54);
            this.txtCCCD.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCCCD.TabIndex = 44;
            this.txtCCCD.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCCCD.TextMarginBottom = 0;
            this.txtCCCD.TextMarginLeft = 3;
            this.txtCCCD.TextMarginTop = 1;
            this.txtCCCD.TextPlaceholder = "";
            this.txtCCCD.UseSystemPasswordChar = false;
            this.txtCCCD.WordWrap = true;
            // 
            // txtDiaChi
            // 
            this.txtDiaChi.AcceptsReturn = false;
            this.txtDiaChi.AcceptsTab = false;
            this.txtDiaChi.AnimationSpeed = 200;
            this.txtDiaChi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDiaChi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDiaChi.AutoSizeHeight = true;
            this.txtDiaChi.BackColor = System.Drawing.Color.Transparent;
            this.txtDiaChi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDiaChi.BackgroundImage")));
            this.txtDiaChi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDiaChi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDiaChi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDiaChi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDiaChi.BorderRadius = 1;
            this.txtDiaChi.BorderThickness = 1;
            this.txtDiaChi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDiaChi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDiaChi.DefaultText = "";
            this.txtDiaChi.FillColor = System.Drawing.Color.White;
            this.txtDiaChi.HideSelection = true;
            this.txtDiaChi.IconLeft = null;
            this.txtDiaChi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.IconPadding = 10;
            this.txtDiaChi.IconRight = null;
            this.txtDiaChi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.Lines = new string[0];
            this.txtDiaChi.Location = new System.Drawing.Point(148, 226);
            this.txtDiaChi.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtDiaChi.MaxLength = 32767;
            this.txtDiaChi.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDiaChi.Modified = false;
            this.txtDiaChi.Multiline = false;
            this.txtDiaChi.Name = "txtDiaChi";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDiaChi.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnIdleState = stateProperties20;
            this.txtDiaChi.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtDiaChi.PasswordChar = '\0';
            this.txtDiaChi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDiaChi.PlaceholderText = "";
            this.txtDiaChi.ReadOnly = false;
            this.txtDiaChi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDiaChi.SelectedText = "";
            this.txtDiaChi.SelectionLength = 0;
            this.txtDiaChi.SelectionStart = 0;
            this.txtDiaChi.ShortcutsEnabled = true;
            this.txtDiaChi.Size = new System.Drawing.Size(555, 54);
            this.txtDiaChi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDiaChi.TabIndex = 43;
            this.txtDiaChi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDiaChi.TextMarginBottom = 0;
            this.txtDiaChi.TextMarginLeft = 3;
            this.txtDiaChi.TextMarginTop = 1;
            this.txtDiaChi.TextPlaceholder = "";
            this.txtDiaChi.UseSystemPasswordChar = false;
            this.txtDiaChi.WordWrap = true;
            // 
            // txtMaNV
            // 
            this.txtMaNV.AcceptsReturn = false;
            this.txtMaNV.AcceptsTab = false;
            this.txtMaNV.AnimationSpeed = 200;
            this.txtMaNV.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMaNV.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMaNV.AutoSizeHeight = true;
            this.txtMaNV.BackColor = System.Drawing.Color.Transparent;
            this.txtMaNV.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMaNV.BackgroundImage")));
            this.txtMaNV.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMaNV.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMaNV.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMaNV.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMaNV.BorderRadius = 1;
            this.txtMaNV.BorderThickness = 1;
            this.txtMaNV.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMaNV.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaNV.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtMaNV.DefaultText = "";
            this.txtMaNV.FillColor = System.Drawing.Color.White;
            this.txtMaNV.HideSelection = true;
            this.txtMaNV.IconLeft = null;
            this.txtMaNV.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaNV.IconPadding = 10;
            this.txtMaNV.IconRight = null;
            this.txtMaNV.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaNV.Lines = new string[0];
            this.txtMaNV.Location = new System.Drawing.Point(148, 42);
            this.txtMaNV.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtMaNV.MaxLength = 32767;
            this.txtMaNV.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMaNV.Modified = false;
            this.txtMaNV.Multiline = false;
            this.txtMaNV.Name = "txtMaNV";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaNV.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMaNV.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaNV.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaNV.OnIdleState = stateProperties24;
            this.txtMaNV.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtMaNV.PasswordChar = '\0';
            this.txtMaNV.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMaNV.PlaceholderText = "";
            this.txtMaNV.ReadOnly = true;
            this.txtMaNV.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMaNV.SelectedText = "";
            this.txtMaNV.SelectionLength = 0;
            this.txtMaNV.SelectionStart = 0;
            this.txtMaNV.ShortcutsEnabled = true;
            this.txtMaNV.Size = new System.Drawing.Size(555, 54);
            this.txtMaNV.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMaNV.TabIndex = 42;
            this.txtMaNV.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMaNV.TextMarginBottom = 0;
            this.txtMaNV.TextMarginLeft = 3;
            this.txtMaNV.TextMarginTop = 1;
            this.txtMaNV.TextPlaceholder = "";
            this.txtMaNV.UseSystemPasswordChar = false;
            this.txtMaNV.WordWrap = true;
            // 
            // btnChonHinhAnh
            // 
            this.btnChonHinhAnh.AllowAnimations = true;
            this.btnChonHinhAnh.AllowMouseEffects = true;
            this.btnChonHinhAnh.AllowToggling = false;
            this.btnChonHinhAnh.AnimationSpeed = 200;
            this.btnChonHinhAnh.AutoGenerateColors = false;
            this.btnChonHinhAnh.AutoRoundBorders = false;
            this.btnChonHinhAnh.AutoSizeLeftIcon = true;
            this.btnChonHinhAnh.AutoSizeRightIcon = true;
            this.btnChonHinhAnh.BackColor = System.Drawing.Color.Transparent;
            this.btnChonHinhAnh.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnChonHinhAnh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnChonHinhAnh.BackgroundImage")));
            this.btnChonHinhAnh.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChonHinhAnh.ButtonText = "Chọn ảnh";
            this.btnChonHinhAnh.ButtonTextMarginLeft = 0;
            this.btnChonHinhAnh.ColorContrastOnClick = 45;
            this.btnChonHinhAnh.ColorContrastOnHover = 45;
            this.btnChonHinhAnh.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnChonHinhAnh.CustomizableEdges = borderEdges1;
            this.btnChonHinhAnh.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnChonHinhAnh.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChonHinhAnh.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnChonHinhAnh.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnChonHinhAnh.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnChonHinhAnh.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnChonHinhAnh.ForeColor = System.Drawing.Color.White;
            this.btnChonHinhAnh.IconLeft = null;
            this.btnChonHinhAnh.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChonHinhAnh.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnChonHinhAnh.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnChonHinhAnh.IconMarginLeft = 11;
            this.btnChonHinhAnh.IconPadding = 10;
            this.btnChonHinhAnh.IconRight = null;
            this.btnChonHinhAnh.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChonHinhAnh.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnChonHinhAnh.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnChonHinhAnh.IconSize = 25;
            this.btnChonHinhAnh.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnChonHinhAnh.IdleBorderRadius = 0;
            this.btnChonHinhAnh.IdleBorderThickness = 0;
            this.btnChonHinhAnh.IdleFillColor = System.Drawing.Color.Empty;
            this.btnChonHinhAnh.IdleIconLeftImage = null;
            this.btnChonHinhAnh.IdleIconRightImage = null;
            this.btnChonHinhAnh.IndicateFocus = false;
            this.btnChonHinhAnh.Location = new System.Drawing.Point(753, 356);
            this.btnChonHinhAnh.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnChonHinhAnh.Name = "btnChonHinhAnh";
            this.btnChonHinhAnh.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChonHinhAnh.OnDisabledState.BorderRadius = 1;
            this.btnChonHinhAnh.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChonHinhAnh.OnDisabledState.BorderThickness = 1;
            this.btnChonHinhAnh.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChonHinhAnh.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChonHinhAnh.OnDisabledState.IconLeftImage = null;
            this.btnChonHinhAnh.OnDisabledState.IconRightImage = null;
            this.btnChonHinhAnh.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnChonHinhAnh.onHoverState.BorderRadius = 1;
            this.btnChonHinhAnh.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChonHinhAnh.onHoverState.BorderThickness = 1;
            this.btnChonHinhAnh.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnChonHinhAnh.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnChonHinhAnh.onHoverState.IconLeftImage = null;
            this.btnChonHinhAnh.onHoverState.IconRightImage = null;
            this.btnChonHinhAnh.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnChonHinhAnh.OnIdleState.BorderRadius = 1;
            this.btnChonHinhAnh.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChonHinhAnh.OnIdleState.BorderThickness = 1;
            this.btnChonHinhAnh.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnChonHinhAnh.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnChonHinhAnh.OnIdleState.IconLeftImage = null;
            this.btnChonHinhAnh.OnIdleState.IconRightImage = null;
            this.btnChonHinhAnh.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChonHinhAnh.OnPressedState.BorderRadius = 1;
            this.btnChonHinhAnh.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChonHinhAnh.OnPressedState.BorderThickness = 1;
            this.btnChonHinhAnh.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChonHinhAnh.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnChonHinhAnh.OnPressedState.IconLeftImage = null;
            this.btnChonHinhAnh.OnPressedState.IconRightImage = null;
            this.btnChonHinhAnh.Size = new System.Drawing.Size(281, 48);
            this.btnChonHinhAnh.TabIndex = 41;
            this.btnChonHinhAnh.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnChonHinhAnh.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnChonHinhAnh.TextMarginLeft = 0;
            this.btnChonHinhAnh.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnChonHinhAnh.UseDefaultRadiusAndThickness = true;
            this.btnChonHinhAnh.Click += new System.EventHandler(this.btnChonHinhAnh_Click);
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(21, 240);
            this.bunifuLabel6.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(73, 28);
            this.bunifuLabel6.TabIndex = 40;
            this.bunifuLabel6.Text = "Địa chỉ : ";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.Location = new System.Drawing.Point(21, 302);
            this.bunifuLabel5.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(64, 28);
            this.bunifuLabel5.TabIndex = 39;
            this.bunifuLabel5.Text = "CCCD : ";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.Location = new System.Drawing.Point(21, 361);
            this.bunifuLabel4.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(76, 28);
            this.bunifuLabel4.TabIndex = 38;
            this.bunifuLabel4.Text = "Liên hệ :";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(21, 178);
            this.bunifuLabel3.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(88, 28);
            this.bunifuLabel3.TabIndex = 37;
            this.bunifuLabel3.Text = "Giới tính : ";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.Location = new System.Drawing.Point(21, 114);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(72, 28);
            this.bunifuLabel2.TabIndex = 36;
            this.bunifuLabel2.Text = "Họ tên : ";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(21, 50);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(71, 28);
            this.bunifuLabel1.TabIndex = 35;
            this.bunifuLabel1.Text = "Mã NV : ";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pnlInfor
            // 
            this.pnlInfor.Controls.Add(this.txtLienHe);
            this.pnlInfor.Controls.Add(this.btnChonHinhAnh);
            this.pnlInfor.Controls.Add(this.picImage);
            this.pnlInfor.Controls.Add(this.txtGioiTinh);
            this.pnlInfor.Controls.Add(this.txtHoTen);
            this.pnlInfor.Controls.Add(this.txtCCCD);
            this.pnlInfor.Controls.Add(this.txtDiaChi);
            this.pnlInfor.Controls.Add(this.txtMaNV);
            this.pnlInfor.Controls.Add(this.bunifuLabel6);
            this.pnlInfor.Controls.Add(this.bunifuLabel5);
            this.pnlInfor.Controls.Add(this.bunifuLabel4);
            this.pnlInfor.Controls.Add(this.bunifuLabel3);
            this.pnlInfor.Controls.Add(this.bunifuLabel2);
            this.pnlInfor.Controls.Add(this.bunifuLabel1);
            this.pnlInfor.Location = new System.Drawing.Point(16, 15);
            this.pnlInfor.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.pnlInfor.Name = "pnlInfor";
            this.pnlInfor.Size = new System.Drawing.Size(1080, 426);
            this.pnlInfor.TabIndex = 49;
            // 
            // btnHuy
            // 
            this.btnHuy.AllowAnimations = true;
            this.btnHuy.AllowMouseEffects = true;
            this.btnHuy.AllowToggling = false;
            this.btnHuy.AnimationSpeed = 200;
            this.btnHuy.AutoGenerateColors = false;
            this.btnHuy.AutoRoundBorders = false;
            this.btnHuy.AutoSizeLeftIcon = true;
            this.btnHuy.AutoSizeRightIcon = true;
            this.btnHuy.BackColor = System.Drawing.Color.Transparent;
            this.btnHuy.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnHuy.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHuy.BackgroundImage")));
            this.btnHuy.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHuy.ButtonText = "Hủy";
            this.btnHuy.ButtonTextMarginLeft = 0;
            this.btnHuy.ColorContrastOnClick = 45;
            this.btnHuy.ColorContrastOnHover = 45;
            this.btnHuy.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnHuy.CustomizableEdges = borderEdges2;
            this.btnHuy.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnHuy.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHuy.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnHuy.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnHuy.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHuy.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnHuy.ForeColor = System.Drawing.Color.White;
            this.btnHuy.IconLeft = null;
            this.btnHuy.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHuy.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnHuy.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHuy.IconMarginLeft = 11;
            this.btnHuy.IconPadding = 10;
            this.btnHuy.IconRight = null;
            this.btnHuy.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHuy.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnHuy.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHuy.IconSize = 25;
            this.btnHuy.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnHuy.IdleBorderRadius = 0;
            this.btnHuy.IdleBorderThickness = 0;
            this.btnHuy.IdleFillColor = System.Drawing.Color.Empty;
            this.btnHuy.IdleIconLeftImage = null;
            this.btnHuy.IdleIconRightImage = null;
            this.btnHuy.IndicateFocus = false;
            this.btnHuy.Location = new System.Drawing.Point(769, 463);
            this.btnHuy.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnHuy.Name = "btnHuy";
            this.btnHuy.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHuy.OnDisabledState.BorderRadius = 1;
            this.btnHuy.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHuy.OnDisabledState.BorderThickness = 1;
            this.btnHuy.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHuy.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHuy.OnDisabledState.IconLeftImage = null;
            this.btnHuy.OnDisabledState.IconRightImage = null;
            this.btnHuy.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnHuy.onHoverState.BorderRadius = 1;
            this.btnHuy.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHuy.onHoverState.BorderThickness = 1;
            this.btnHuy.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnHuy.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnHuy.onHoverState.IconLeftImage = null;
            this.btnHuy.onHoverState.IconRightImage = null;
            this.btnHuy.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnHuy.OnIdleState.BorderRadius = 1;
            this.btnHuy.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHuy.OnIdleState.BorderThickness = 1;
            this.btnHuy.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnHuy.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnHuy.OnIdleState.IconLeftImage = null;
            this.btnHuy.OnIdleState.IconRightImage = null;
            this.btnHuy.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnHuy.OnPressedState.BorderRadius = 1;
            this.btnHuy.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHuy.OnPressedState.BorderThickness = 1;
            this.btnHuy.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnHuy.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnHuy.OnPressedState.IconLeftImage = null;
            this.btnHuy.OnPressedState.IconRightImage = null;
            this.btnHuy.Size = new System.Drawing.Size(281, 48);
            this.btnHuy.TabIndex = 49;
            this.btnHuy.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHuy.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHuy.TextMarginLeft = 0;
            this.btnHuy.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnHuy.UseDefaultRadiusAndThickness = true;
            // 
            // btnLuu
            // 
            this.btnLuu.AllowAnimations = true;
            this.btnLuu.AllowMouseEffects = true;
            this.btnLuu.AllowToggling = false;
            this.btnLuu.AnimationSpeed = 200;
            this.btnLuu.AutoGenerateColors = false;
            this.btnLuu.AutoRoundBorders = false;
            this.btnLuu.AutoSizeLeftIcon = true;
            this.btnLuu.AutoSizeRightIcon = true;
            this.btnLuu.BackColor = System.Drawing.Color.Transparent;
            this.btnLuu.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnLuu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLuu.BackgroundImage")));
            this.btnLuu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuu.ButtonText = "Lưu";
            this.btnLuu.ButtonTextMarginLeft = 0;
            this.btnLuu.ColorContrastOnClick = 45;
            this.btnLuu.ColorContrastOnHover = 45;
            this.btnLuu.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnLuu.CustomizableEdges = borderEdges3;
            this.btnLuu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLuu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLuu.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnLuu.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnLuu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLuu.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLuu.ForeColor = System.Drawing.Color.White;
            this.btnLuu.IconLeft = null;
            this.btnLuu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLuu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLuu.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLuu.IconMarginLeft = 11;
            this.btnLuu.IconPadding = 10;
            this.btnLuu.IconRight = null;
            this.btnLuu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLuu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLuu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLuu.IconSize = 25;
            this.btnLuu.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnLuu.IdleBorderRadius = 0;
            this.btnLuu.IdleBorderThickness = 0;
            this.btnLuu.IdleFillColor = System.Drawing.Color.Empty;
            this.btnLuu.IdleIconLeftImage = null;
            this.btnLuu.IdleIconRightImage = null;
            this.btnLuu.IndicateFocus = false;
            this.btnLuu.Location = new System.Drawing.Point(437, 463);
            this.btnLuu.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnLuu.Name = "btnLuu";
            this.btnLuu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLuu.OnDisabledState.BorderRadius = 1;
            this.btnLuu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuu.OnDisabledState.BorderThickness = 1;
            this.btnLuu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLuu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLuu.OnDisabledState.IconLeftImage = null;
            this.btnLuu.OnDisabledState.IconRightImage = null;
            this.btnLuu.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnLuu.onHoverState.BorderRadius = 1;
            this.btnLuu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuu.onHoverState.BorderThickness = 1;
            this.btnLuu.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnLuu.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLuu.onHoverState.IconLeftImage = null;
            this.btnLuu.onHoverState.IconRightImage = null;
            this.btnLuu.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnLuu.OnIdleState.BorderRadius = 1;
            this.btnLuu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuu.OnIdleState.BorderThickness = 1;
            this.btnLuu.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnLuu.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLuu.OnIdleState.IconLeftImage = null;
            this.btnLuu.OnIdleState.IconRightImage = null;
            this.btnLuu.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLuu.OnPressedState.BorderRadius = 1;
            this.btnLuu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLuu.OnPressedState.BorderThickness = 1;
            this.btnLuu.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLuu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLuu.OnPressedState.IconLeftImage = null;
            this.btnLuu.OnPressedState.IconRightImage = null;
            this.btnLuu.Size = new System.Drawing.Size(281, 48);
            this.btnLuu.TabIndex = 50;
            this.btnLuu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLuu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLuu.TextMarginLeft = 0;
            this.btnLuu.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLuu.UseDefaultRadiusAndThickness = true;
            this.btnLuu.Click += new System.EventHandler(this.btnLuu_Click);
            // 
            // frmDoiThongTinCaNhan
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1112, 526);
            this.Controls.Add(this.btnLuu);
            this.Controls.Add(this.btnHuy);
            this.Controls.Add(this.pnlInfor);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Name = "frmDoiThongTinCaNhan";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmDoiThongTinCaNhan";
            ((System.ComponentModel.ISupportInitialize)(this.picImage)).EndInit();
            this.pnlInfor.ResumeLayout(false);
            this.pnlInfor.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.PictureBox picImage;
        private Bunifu.UI.WinForms.BunifuTextBox txtLienHe;
        private Bunifu.UI.WinForms.BunifuTextBox txtGioiTinh;
        private Bunifu.UI.WinForms.BunifuTextBox txtHoTen;
        private Bunifu.UI.WinForms.BunifuTextBox txtCCCD;
        private Bunifu.UI.WinForms.BunifuTextBox txtDiaChi;
        private Bunifu.UI.WinForms.BunifuTextBox txtMaNV;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnChonHinhAnh;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.Panel pnlInfor;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHuy;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLuu;
    }
}