
namespace management_store
{
    partial class frmNhaSanXuat
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmNhaSanXuat));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.panel1 = new System.Windows.Forms.Panel();
            this.label7 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.dgvNhaSanXuat = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnDong = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnXoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCapNhat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnThem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtTenNhaSanXuat = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtKhuVuc = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtZipCode = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtDiaChi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtWebsite = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtLienHe = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuSeparator3 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuSeparator2 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.dragMove = new Bunifu.Framework.UI.BunifuDragControl(this.components);
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNhaSanXuat)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.label7);
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(827, 68);
            this.panel1.TabIndex = 0;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Open Sans", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label7.Location = new System.Drawing.Point(302, 14);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(225, 39);
            this.label7.TabIndex = 9;
            this.label7.Text = "NHÀ CUNG CẤP";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Open Sans", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label2.Location = new System.Drawing.Point(13, 97);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(89, 27);
            this.label2.TabIndex = 16;
            this.label2.Text = "Tên NSX";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Open Sans", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label3.Location = new System.Drawing.Point(13, 144);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(76, 27);
            this.label3.TabIndex = 11;
            this.label3.Text = "Địa chỉ";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Open Sans", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label1.Location = new System.Drawing.Point(13, 192);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(80, 27);
            this.label1.TabIndex = 12;
            this.label1.Text = "Liên hệ";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Open Sans", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label6.Location = new System.Drawing.Point(428, 192);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(89, 27);
            this.label6.TabIndex = 13;
            this.label6.Text = "Khu vực";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Open Sans", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label4.Location = new System.Drawing.Point(428, 97);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(87, 27);
            this.label4.TabIndex = 14;
            this.label4.Text = "Website";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Open Sans", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label5.Location = new System.Drawing.Point(428, 144);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(91, 27);
            this.label5.TabIndex = 15;
            this.label5.Text = "Zip code";
            // 
            // dgvNhaSanXuat
            // 
            this.dgvNhaSanXuat.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.dgvNhaSanXuat.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.dgvNhaSanXuat.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvNhaSanXuat.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvNhaSanXuat.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvNhaSanXuat.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvNhaSanXuat.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.dgvNhaSanXuat.ColumnHeadersHeight = 40;
            this.dgvNhaSanXuat.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgvNhaSanXuat.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvNhaSanXuat.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvNhaSanXuat.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvNhaSanXuat.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvNhaSanXuat.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgvNhaSanXuat.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvNhaSanXuat.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgvNhaSanXuat.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvNhaSanXuat.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvNhaSanXuat.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgvNhaSanXuat.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvNhaSanXuat.CurrentTheme.Name = null;
            this.dgvNhaSanXuat.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgvNhaSanXuat.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvNhaSanXuat.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvNhaSanXuat.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvNhaSanXuat.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvNhaSanXuat.DefaultCellStyle = dataGridViewCellStyle6;
            this.dgvNhaSanXuat.EditMode = System.Windows.Forms.DataGridViewEditMode.EditProgrammatically;
            this.dgvNhaSanXuat.EnableHeadersVisualStyles = false;
            this.dgvNhaSanXuat.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvNhaSanXuat.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgvNhaSanXuat.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvNhaSanXuat.HeaderForeColor = System.Drawing.Color.White;
            this.dgvNhaSanXuat.Location = new System.Drawing.Point(18, 252);
            this.dgvNhaSanXuat.Name = "dgvNhaSanXuat";
            this.dgvNhaSanXuat.RowHeadersVisible = false;
            this.dgvNhaSanXuat.RowTemplate.Height = 40;
            this.dgvNhaSanXuat.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvNhaSanXuat.Size = new System.Drawing.Size(790, 324);
            this.dgvNhaSanXuat.TabIndex = 23;
            this.dgvNhaSanXuat.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dgvNhaSanXuat.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvNhaSanXuat_CellContentClick);
            this.dgvNhaSanXuat.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvNhaSanXuat_CellContentClick);
            // 
            // btnDong
            // 
            this.btnDong.AllowAnimations = true;
            this.btnDong.AllowMouseEffects = true;
            this.btnDong.AllowToggling = false;
            this.btnDong.AnimationSpeed = 200;
            this.btnDong.AutoGenerateColors = false;
            this.btnDong.AutoRoundBorders = false;
            this.btnDong.AutoSizeLeftIcon = true;
            this.btnDong.AutoSizeRightIcon = true;
            this.btnDong.BackColor = System.Drawing.Color.Transparent;
            this.btnDong.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnDong.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDong.BackgroundImage")));
            this.btnDong.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDong.ButtonText = "Đóng";
            this.btnDong.ButtonTextMarginLeft = 0;
            this.btnDong.ColorContrastOnClick = 45;
            this.btnDong.ColorContrastOnHover = 45;
            this.btnDong.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnDong.CustomizableEdges = borderEdges5;
            this.btnDong.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDong.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDong.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnDong.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnDong.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDong.Font = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDong.ForeColor = System.Drawing.Color.White;
            this.btnDong.IconLeft = null;
            this.btnDong.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDong.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDong.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDong.IconMarginLeft = 11;
            this.btnDong.IconPadding = 10;
            this.btnDong.IconRight = null;
            this.btnDong.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDong.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDong.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDong.IconSize = 25;
            this.btnDong.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnDong.IdleBorderRadius = 0;
            this.btnDong.IdleBorderThickness = 0;
            this.btnDong.IdleFillColor = System.Drawing.Color.Empty;
            this.btnDong.IdleIconLeftImage = null;
            this.btnDong.IdleIconRightImage = null;
            this.btnDong.IndicateFocus = false;
            this.btnDong.Location = new System.Drawing.Point(678, 597);
            this.btnDong.Name = "btnDong";
            this.btnDong.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDong.OnDisabledState.BorderRadius = 1;
            this.btnDong.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDong.OnDisabledState.BorderThickness = 1;
            this.btnDong.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDong.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDong.OnDisabledState.IconLeftImage = null;
            this.btnDong.OnDisabledState.IconRightImage = null;
            this.btnDong.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnDong.onHoverState.BorderRadius = 1;
            this.btnDong.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDong.onHoverState.BorderThickness = 1;
            this.btnDong.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnDong.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDong.onHoverState.IconLeftImage = null;
            this.btnDong.onHoverState.IconRightImage = null;
            this.btnDong.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDong.OnIdleState.BorderRadius = 1;
            this.btnDong.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDong.OnIdleState.BorderThickness = 1;
            this.btnDong.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnDong.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDong.OnIdleState.IconLeftImage = null;
            this.btnDong.OnIdleState.IconRightImage = null;
            this.btnDong.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDong.OnPressedState.BorderRadius = 1;
            this.btnDong.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDong.OnPressedState.BorderThickness = 1;
            this.btnDong.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDong.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDong.OnPressedState.IconLeftImage = null;
            this.btnDong.OnPressedState.IconRightImage = null;
            this.btnDong.Size = new System.Drawing.Size(130, 39);
            this.btnDong.TabIndex = 24;
            this.btnDong.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDong.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDong.TextMarginLeft = 0;
            this.btnDong.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDong.UseDefaultRadiusAndThickness = true;
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            // 
            // btnXoa
            // 
            this.btnXoa.AllowAnimations = true;
            this.btnXoa.AllowMouseEffects = true;
            this.btnXoa.AllowToggling = false;
            this.btnXoa.AnimationSpeed = 200;
            this.btnXoa.AutoGenerateColors = false;
            this.btnXoa.AutoRoundBorders = false;
            this.btnXoa.AutoSizeLeftIcon = true;
            this.btnXoa.AutoSizeRightIcon = true;
            this.btnXoa.BackColor = System.Drawing.Color.Transparent;
            this.btnXoa.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnXoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXoa.BackgroundImage")));
            this.btnXoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.ButtonText = "Xóa";
            this.btnXoa.ButtonTextMarginLeft = 0;
            this.btnXoa.ColorContrastOnClick = 45;
            this.btnXoa.ColorContrastOnHover = 45;
            this.btnXoa.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnXoa.CustomizableEdges = borderEdges6;
            this.btnXoa.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXoa.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoa.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnXoa.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnXoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXoa.Font = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnXoa.ForeColor = System.Drawing.Color.White;
            this.btnXoa.IconLeft = null;
            this.btnXoa.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnXoa.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoa.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnXoa.IconMarginLeft = 11;
            this.btnXoa.IconPadding = 10;
            this.btnXoa.IconRight = null;
            this.btnXoa.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnXoa.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoa.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnXoa.IconSize = 25;
            this.btnXoa.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnXoa.IdleBorderRadius = 0;
            this.btnXoa.IdleBorderThickness = 0;
            this.btnXoa.IdleFillColor = System.Drawing.Color.Empty;
            this.btnXoa.IdleIconLeftImage = null;
            this.btnXoa.IdleIconRightImage = null;
            this.btnXoa.IndicateFocus = false;
            this.btnXoa.Location = new System.Drawing.Point(515, 597);
            this.btnXoa.Name = "btnXoa";
            this.btnXoa.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoa.OnDisabledState.BorderRadius = 1;
            this.btnXoa.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.OnDisabledState.BorderThickness = 1;
            this.btnXoa.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoa.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoa.OnDisabledState.IconLeftImage = null;
            this.btnXoa.OnDisabledState.IconRightImage = null;
            this.btnXoa.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnXoa.onHoverState.BorderRadius = 1;
            this.btnXoa.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.onHoverState.BorderThickness = 1;
            this.btnXoa.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnXoa.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnXoa.onHoverState.IconLeftImage = null;
            this.btnXoa.onHoverState.IconRightImage = null;
            this.btnXoa.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnXoa.OnIdleState.BorderRadius = 1;
            this.btnXoa.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.OnIdleState.BorderThickness = 1;
            this.btnXoa.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnXoa.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnXoa.OnIdleState.IconLeftImage = null;
            this.btnXoa.OnIdleState.IconRightImage = null;
            this.btnXoa.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXoa.OnPressedState.BorderRadius = 1;
            this.btnXoa.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.OnPressedState.BorderThickness = 1;
            this.btnXoa.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXoa.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnXoa.OnPressedState.IconLeftImage = null;
            this.btnXoa.OnPressedState.IconRightImage = null;
            this.btnXoa.Size = new System.Drawing.Size(130, 39);
            this.btnXoa.TabIndex = 24;
            this.btnXoa.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXoa.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnXoa.TextMarginLeft = 0;
            this.btnXoa.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnXoa.UseDefaultRadiusAndThickness = true;
            this.btnXoa.Click += new System.EventHandler(this.btnXoa_Click);
            // 
            // btnCapNhat
            // 
            this.btnCapNhat.AllowAnimations = true;
            this.btnCapNhat.AllowMouseEffects = true;
            this.btnCapNhat.AllowToggling = false;
            this.btnCapNhat.AnimationSpeed = 200;
            this.btnCapNhat.AutoGenerateColors = false;
            this.btnCapNhat.AutoRoundBorders = false;
            this.btnCapNhat.AutoSizeLeftIcon = true;
            this.btnCapNhat.AutoSizeRightIcon = true;
            this.btnCapNhat.BackColor = System.Drawing.Color.Transparent;
            this.btnCapNhat.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCapNhat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCapNhat.BackgroundImage")));
            this.btnCapNhat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCapNhat.ButtonText = "Cập nhật";
            this.btnCapNhat.ButtonTextMarginLeft = 0;
            this.btnCapNhat.ColorContrastOnClick = 45;
            this.btnCapNhat.ColorContrastOnHover = 45;
            this.btnCapNhat.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnCapNhat.CustomizableEdges = borderEdges7;
            this.btnCapNhat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCapNhat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCapNhat.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCapNhat.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCapNhat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCapNhat.Font = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCapNhat.ForeColor = System.Drawing.Color.White;
            this.btnCapNhat.IconLeft = null;
            this.btnCapNhat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCapNhat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCapNhat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCapNhat.IconMarginLeft = 11;
            this.btnCapNhat.IconPadding = 10;
            this.btnCapNhat.IconRight = null;
            this.btnCapNhat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCapNhat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCapNhat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCapNhat.IconSize = 25;
            this.btnCapNhat.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCapNhat.IdleBorderRadius = 0;
            this.btnCapNhat.IdleBorderThickness = 0;
            this.btnCapNhat.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCapNhat.IdleIconLeftImage = null;
            this.btnCapNhat.IdleIconRightImage = null;
            this.btnCapNhat.IndicateFocus = false;
            this.btnCapNhat.Location = new System.Drawing.Point(352, 597);
            this.btnCapNhat.Name = "btnCapNhat";
            this.btnCapNhat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCapNhat.OnDisabledState.BorderRadius = 1;
            this.btnCapNhat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCapNhat.OnDisabledState.BorderThickness = 1;
            this.btnCapNhat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCapNhat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCapNhat.OnDisabledState.IconLeftImage = null;
            this.btnCapNhat.OnDisabledState.IconRightImage = null;
            this.btnCapNhat.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCapNhat.onHoverState.BorderRadius = 1;
            this.btnCapNhat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCapNhat.onHoverState.BorderThickness = 1;
            this.btnCapNhat.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCapNhat.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCapNhat.onHoverState.IconLeftImage = null;
            this.btnCapNhat.onHoverState.IconRightImage = null;
            this.btnCapNhat.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCapNhat.OnIdleState.BorderRadius = 1;
            this.btnCapNhat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCapNhat.OnIdleState.BorderThickness = 1;
            this.btnCapNhat.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCapNhat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCapNhat.OnIdleState.IconLeftImage = null;
            this.btnCapNhat.OnIdleState.IconRightImage = null;
            this.btnCapNhat.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCapNhat.OnPressedState.BorderRadius = 1;
            this.btnCapNhat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCapNhat.OnPressedState.BorderThickness = 1;
            this.btnCapNhat.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCapNhat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCapNhat.OnPressedState.IconLeftImage = null;
            this.btnCapNhat.OnPressedState.IconRightImage = null;
            this.btnCapNhat.Size = new System.Drawing.Size(130, 39);
            this.btnCapNhat.TabIndex = 24;
            this.btnCapNhat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCapNhat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCapNhat.TextMarginLeft = 0;
            this.btnCapNhat.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCapNhat.UseDefaultRadiusAndThickness = true;
            this.btnCapNhat.Click += new System.EventHandler(this.btnCapNhat_Click);
            // 
            // btnThem
            // 
            this.btnThem.AllowAnimations = true;
            this.btnThem.AllowMouseEffects = true;
            this.btnThem.AllowToggling = false;
            this.btnThem.AnimationSpeed = 200;
            this.btnThem.AutoGenerateColors = false;
            this.btnThem.AutoRoundBorders = false;
            this.btnThem.AutoSizeLeftIcon = true;
            this.btnThem.AutoSizeRightIcon = true;
            this.btnThem.BackColor = System.Drawing.Color.Transparent;
            this.btnThem.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnThem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThem.BackgroundImage")));
            this.btnThem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.ButtonText = "Thêm";
            this.btnThem.ButtonTextMarginLeft = 0;
            this.btnThem.ColorContrastOnClick = 45;
            this.btnThem.ColorContrastOnHover = 45;
            this.btnThem.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnThem.CustomizableEdges = borderEdges8;
            this.btnThem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThem.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnThem.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnThem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThem.Font = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnThem.ForeColor = System.Drawing.Color.White;
            this.btnThem.IconLeft = null;
            this.btnThem.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThem.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnThem.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnThem.IconMarginLeft = 11;
            this.btnThem.IconPadding = 10;
            this.btnThem.IconRight = null;
            this.btnThem.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThem.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnThem.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThem.IconSize = 25;
            this.btnThem.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnThem.IdleBorderRadius = 0;
            this.btnThem.IdleBorderThickness = 0;
            this.btnThem.IdleFillColor = System.Drawing.Color.Empty;
            this.btnThem.IdleIconLeftImage = null;
            this.btnThem.IdleIconRightImage = null;
            this.btnThem.IndicateFocus = false;
            this.btnThem.Location = new System.Drawing.Point(189, 597);
            this.btnThem.Name = "btnThem";
            this.btnThem.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThem.OnDisabledState.BorderRadius = 1;
            this.btnThem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnDisabledState.BorderThickness = 1;
            this.btnThem.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThem.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThem.OnDisabledState.IconLeftImage = null;
            this.btnThem.OnDisabledState.IconRightImage = null;
            this.btnThem.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnThem.onHoverState.BorderRadius = 1;
            this.btnThem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.onHoverState.BorderThickness = 1;
            this.btnThem.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnThem.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnThem.onHoverState.IconLeftImage = null;
            this.btnThem.onHoverState.IconRightImage = null;
            this.btnThem.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnThem.OnIdleState.BorderRadius = 1;
            this.btnThem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnIdleState.BorderThickness = 1;
            this.btnThem.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnThem.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnThem.OnIdleState.IconLeftImage = null;
            this.btnThem.OnIdleState.IconRightImage = null;
            this.btnThem.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThem.OnPressedState.BorderRadius = 1;
            this.btnThem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnPressedState.BorderThickness = 1;
            this.btnThem.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThem.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnThem.OnPressedState.IconLeftImage = null;
            this.btnThem.OnPressedState.IconRightImage = null;
            this.btnThem.Size = new System.Drawing.Size(130, 39);
            this.btnThem.TabIndex = 25;
            this.btnThem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThem.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThem.TextMarginLeft = 0;
            this.btnThem.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnThem.UseDefaultRadiusAndThickness = true;
            this.btnThem.Click += new System.EventHandler(this.btnThem_Click);
            // 
            // txtTenNhaSanXuat
            // 
            this.txtTenNhaSanXuat.AcceptsReturn = false;
            this.txtTenNhaSanXuat.AcceptsTab = false;
            this.txtTenNhaSanXuat.AnimationSpeed = 200;
            this.txtTenNhaSanXuat.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTenNhaSanXuat.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTenNhaSanXuat.AutoSizeHeight = true;
            this.txtTenNhaSanXuat.BackColor = System.Drawing.Color.Transparent;
            this.txtTenNhaSanXuat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTenNhaSanXuat.BackgroundImage")));
            this.txtTenNhaSanXuat.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTenNhaSanXuat.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTenNhaSanXuat.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTenNhaSanXuat.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTenNhaSanXuat.BorderRadius = 1;
            this.txtTenNhaSanXuat.BorderThickness = 1;
            this.txtTenNhaSanXuat.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTenNhaSanXuat.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNhaSanXuat.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTenNhaSanXuat.DefaultText = "";
            this.txtTenNhaSanXuat.FillColor = System.Drawing.Color.White;
            this.txtTenNhaSanXuat.HideSelection = true;
            this.txtTenNhaSanXuat.IconLeft = null;
            this.txtTenNhaSanXuat.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNhaSanXuat.IconPadding = 10;
            this.txtTenNhaSanXuat.IconRight = null;
            this.txtTenNhaSanXuat.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNhaSanXuat.Lines = new string[0];
            this.txtTenNhaSanXuat.Location = new System.Drawing.Point(122, 91);
            this.txtTenNhaSanXuat.MaxLength = 32767;
            this.txtTenNhaSanXuat.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTenNhaSanXuat.Modified = false;
            this.txtTenNhaSanXuat.Multiline = false;
            this.txtTenNhaSanXuat.Name = "txtTenNhaSanXuat";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNhaSanXuat.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTenNhaSanXuat.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNhaSanXuat.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNhaSanXuat.OnIdleState = stateProperties28;
            this.txtTenNhaSanXuat.Padding = new System.Windows.Forms.Padding(3);
            this.txtTenNhaSanXuat.PasswordChar = '\0';
            this.txtTenNhaSanXuat.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTenNhaSanXuat.PlaceholderText = "Nhập";
            this.txtTenNhaSanXuat.ReadOnly = true;
            this.txtTenNhaSanXuat.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTenNhaSanXuat.SelectedText = "";
            this.txtTenNhaSanXuat.SelectionLength = 0;
            this.txtTenNhaSanXuat.SelectionStart = 0;
            this.txtTenNhaSanXuat.ShortcutsEnabled = true;
            this.txtTenNhaSanXuat.Size = new System.Drawing.Size(272, 39);
            this.txtTenNhaSanXuat.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTenNhaSanXuat.TabIndex = 22;
            this.txtTenNhaSanXuat.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTenNhaSanXuat.TextMarginBottom = 0;
            this.txtTenNhaSanXuat.TextMarginLeft = 3;
            this.txtTenNhaSanXuat.TextMarginTop = 1;
            this.txtTenNhaSanXuat.TextPlaceholder = "Nhập";
            this.txtTenNhaSanXuat.UseSystemPasswordChar = false;
            this.txtTenNhaSanXuat.WordWrap = true;
            // 
            // txtKhuVuc
            // 
            this.txtKhuVuc.AcceptsReturn = false;
            this.txtKhuVuc.AcceptsTab = false;
            this.txtKhuVuc.AnimationSpeed = 200;
            this.txtKhuVuc.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtKhuVuc.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtKhuVuc.AutoSizeHeight = true;
            this.txtKhuVuc.BackColor = System.Drawing.Color.Transparent;
            this.txtKhuVuc.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtKhuVuc.BackgroundImage")));
            this.txtKhuVuc.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtKhuVuc.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtKhuVuc.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtKhuVuc.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtKhuVuc.BorderRadius = 1;
            this.txtKhuVuc.BorderThickness = 1;
            this.txtKhuVuc.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtKhuVuc.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtKhuVuc.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtKhuVuc.DefaultText = "";
            this.txtKhuVuc.FillColor = System.Drawing.Color.White;
            this.txtKhuVuc.HideSelection = true;
            this.txtKhuVuc.IconLeft = null;
            this.txtKhuVuc.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtKhuVuc.IconPadding = 10;
            this.txtKhuVuc.IconRight = null;
            this.txtKhuVuc.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtKhuVuc.Lines = new string[0];
            this.txtKhuVuc.Location = new System.Drawing.Point(536, 183);
            this.txtKhuVuc.MaxLength = 32767;
            this.txtKhuVuc.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtKhuVuc.Modified = false;
            this.txtKhuVuc.Multiline = false;
            this.txtKhuVuc.Name = "txtKhuVuc";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtKhuVuc.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtKhuVuc.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtKhuVuc.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtKhuVuc.OnIdleState = stateProperties32;
            this.txtKhuVuc.Padding = new System.Windows.Forms.Padding(3);
            this.txtKhuVuc.PasswordChar = '\0';
            this.txtKhuVuc.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtKhuVuc.PlaceholderText = "Nhập";
            this.txtKhuVuc.ReadOnly = true;
            this.txtKhuVuc.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtKhuVuc.SelectedText = "";
            this.txtKhuVuc.SelectionLength = 0;
            this.txtKhuVuc.SelectionStart = 0;
            this.txtKhuVuc.ShortcutsEnabled = true;
            this.txtKhuVuc.Size = new System.Drawing.Size(272, 39);
            this.txtKhuVuc.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtKhuVuc.TabIndex = 17;
            this.txtKhuVuc.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtKhuVuc.TextMarginBottom = 0;
            this.txtKhuVuc.TextMarginLeft = 3;
            this.txtKhuVuc.TextMarginTop = 1;
            this.txtKhuVuc.TextPlaceholder = "Nhập";
            this.txtKhuVuc.UseSystemPasswordChar = false;
            this.txtKhuVuc.WordWrap = true;
            // 
            // txtZipCode
            // 
            this.txtZipCode.AcceptsReturn = false;
            this.txtZipCode.AcceptsTab = false;
            this.txtZipCode.AnimationSpeed = 200;
            this.txtZipCode.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtZipCode.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtZipCode.AutoSizeHeight = true;
            this.txtZipCode.BackColor = System.Drawing.Color.Transparent;
            this.txtZipCode.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtZipCode.BackgroundImage")));
            this.txtZipCode.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtZipCode.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtZipCode.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtZipCode.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtZipCode.BorderRadius = 1;
            this.txtZipCode.BorderThickness = 1;
            this.txtZipCode.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtZipCode.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtZipCode.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtZipCode.DefaultText = "";
            this.txtZipCode.FillColor = System.Drawing.Color.White;
            this.txtZipCode.HideSelection = true;
            this.txtZipCode.IconLeft = null;
            this.txtZipCode.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtZipCode.IconPadding = 10;
            this.txtZipCode.IconRight = null;
            this.txtZipCode.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtZipCode.Lines = new string[0];
            this.txtZipCode.Location = new System.Drawing.Point(536, 138);
            this.txtZipCode.MaxLength = 32767;
            this.txtZipCode.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtZipCode.Modified = false;
            this.txtZipCode.Multiline = false;
            this.txtZipCode.Name = "txtZipCode";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtZipCode.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtZipCode.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtZipCode.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtZipCode.OnIdleState = stateProperties36;
            this.txtZipCode.Padding = new System.Windows.Forms.Padding(3);
            this.txtZipCode.PasswordChar = '\0';
            this.txtZipCode.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtZipCode.PlaceholderText = "Nhập";
            this.txtZipCode.ReadOnly = true;
            this.txtZipCode.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtZipCode.SelectedText = "";
            this.txtZipCode.SelectionLength = 0;
            this.txtZipCode.SelectionStart = 0;
            this.txtZipCode.ShortcutsEnabled = true;
            this.txtZipCode.Size = new System.Drawing.Size(272, 39);
            this.txtZipCode.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtZipCode.TabIndex = 18;
            this.txtZipCode.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtZipCode.TextMarginBottom = 0;
            this.txtZipCode.TextMarginLeft = 3;
            this.txtZipCode.TextMarginTop = 1;
            this.txtZipCode.TextPlaceholder = "Nhập";
            this.txtZipCode.UseSystemPasswordChar = false;
            this.txtZipCode.WordWrap = true;
            // 
            // txtDiaChi
            // 
            this.txtDiaChi.AcceptsReturn = false;
            this.txtDiaChi.AcceptsTab = false;
            this.txtDiaChi.AnimationSpeed = 200;
            this.txtDiaChi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDiaChi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDiaChi.AutoSizeHeight = true;
            this.txtDiaChi.BackColor = System.Drawing.Color.Transparent;
            this.txtDiaChi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDiaChi.BackgroundImage")));
            this.txtDiaChi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDiaChi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDiaChi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDiaChi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDiaChi.BorderRadius = 1;
            this.txtDiaChi.BorderThickness = 1;
            this.txtDiaChi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDiaChi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDiaChi.DefaultText = "";
            this.txtDiaChi.FillColor = System.Drawing.Color.White;
            this.txtDiaChi.HideSelection = true;
            this.txtDiaChi.IconLeft = null;
            this.txtDiaChi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.IconPadding = 10;
            this.txtDiaChi.IconRight = null;
            this.txtDiaChi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.Lines = new string[0];
            this.txtDiaChi.Location = new System.Drawing.Point(122, 138);
            this.txtDiaChi.MaxLength = 32767;
            this.txtDiaChi.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDiaChi.Modified = false;
            this.txtDiaChi.Multiline = false;
            this.txtDiaChi.Name = "txtDiaChi";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDiaChi.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnIdleState = stateProperties40;
            this.txtDiaChi.Padding = new System.Windows.Forms.Padding(3);
            this.txtDiaChi.PasswordChar = '\0';
            this.txtDiaChi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDiaChi.PlaceholderText = "Nhập";
            this.txtDiaChi.ReadOnly = true;
            this.txtDiaChi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDiaChi.SelectedText = "";
            this.txtDiaChi.SelectionLength = 0;
            this.txtDiaChi.SelectionStart = 0;
            this.txtDiaChi.ShortcutsEnabled = true;
            this.txtDiaChi.Size = new System.Drawing.Size(272, 39);
            this.txtDiaChi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDiaChi.TabIndex = 19;
            this.txtDiaChi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDiaChi.TextMarginBottom = 0;
            this.txtDiaChi.TextMarginLeft = 3;
            this.txtDiaChi.TextMarginTop = 1;
            this.txtDiaChi.TextPlaceholder = "Nhập";
            this.txtDiaChi.UseSystemPasswordChar = false;
            this.txtDiaChi.WordWrap = true;
            // 
            // txtWebsite
            // 
            this.txtWebsite.AcceptsReturn = false;
            this.txtWebsite.AcceptsTab = false;
            this.txtWebsite.AnimationSpeed = 200;
            this.txtWebsite.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtWebsite.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtWebsite.AutoSizeHeight = true;
            this.txtWebsite.BackColor = System.Drawing.Color.Transparent;
            this.txtWebsite.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtWebsite.BackgroundImage")));
            this.txtWebsite.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtWebsite.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtWebsite.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtWebsite.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtWebsite.BorderRadius = 1;
            this.txtWebsite.BorderThickness = 1;
            this.txtWebsite.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtWebsite.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtWebsite.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtWebsite.DefaultText = "";
            this.txtWebsite.FillColor = System.Drawing.Color.White;
            this.txtWebsite.HideSelection = true;
            this.txtWebsite.IconLeft = null;
            this.txtWebsite.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtWebsite.IconPadding = 10;
            this.txtWebsite.IconRight = null;
            this.txtWebsite.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtWebsite.Lines = new string[0];
            this.txtWebsite.Location = new System.Drawing.Point(536, 91);
            this.txtWebsite.MaxLength = 32767;
            this.txtWebsite.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtWebsite.Modified = false;
            this.txtWebsite.Multiline = false;
            this.txtWebsite.Name = "txtWebsite";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtWebsite.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtWebsite.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtWebsite.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtWebsite.OnIdleState = stateProperties44;
            this.txtWebsite.Padding = new System.Windows.Forms.Padding(3);
            this.txtWebsite.PasswordChar = '\0';
            this.txtWebsite.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtWebsite.PlaceholderText = "Nhập";
            this.txtWebsite.ReadOnly = true;
            this.txtWebsite.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtWebsite.SelectedText = "";
            this.txtWebsite.SelectionLength = 0;
            this.txtWebsite.SelectionStart = 0;
            this.txtWebsite.ShortcutsEnabled = true;
            this.txtWebsite.Size = new System.Drawing.Size(272, 39);
            this.txtWebsite.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtWebsite.TabIndex = 20;
            this.txtWebsite.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtWebsite.TextMarginBottom = 0;
            this.txtWebsite.TextMarginLeft = 3;
            this.txtWebsite.TextMarginTop = 1;
            this.txtWebsite.TextPlaceholder = "Nhập";
            this.txtWebsite.UseSystemPasswordChar = false;
            this.txtWebsite.WordWrap = true;
            // 
            // txtLienHe
            // 
            this.txtLienHe.AcceptsReturn = false;
            this.txtLienHe.AcceptsTab = false;
            this.txtLienHe.AnimationSpeed = 200;
            this.txtLienHe.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtLienHe.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtLienHe.AutoSizeHeight = true;
            this.txtLienHe.BackColor = System.Drawing.Color.Transparent;
            this.txtLienHe.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtLienHe.BackgroundImage")));
            this.txtLienHe.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtLienHe.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtLienHe.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtLienHe.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtLienHe.BorderRadius = 1;
            this.txtLienHe.BorderThickness = 1;
            this.txtLienHe.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtLienHe.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLienHe.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtLienHe.DefaultText = "";
            this.txtLienHe.FillColor = System.Drawing.Color.White;
            this.txtLienHe.HideSelection = true;
            this.txtLienHe.IconLeft = null;
            this.txtLienHe.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLienHe.IconPadding = 10;
            this.txtLienHe.IconRight = null;
            this.txtLienHe.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLienHe.Lines = new string[0];
            this.txtLienHe.Location = new System.Drawing.Point(122, 183);
            this.txtLienHe.MaxLength = 32767;
            this.txtLienHe.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtLienHe.Modified = false;
            this.txtLienHe.Multiline = false;
            this.txtLienHe.Name = "txtLienHe";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLienHe.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtLienHe.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLienHe.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLienHe.OnIdleState = stateProperties48;
            this.txtLienHe.Padding = new System.Windows.Forms.Padding(3);
            this.txtLienHe.PasswordChar = '\0';
            this.txtLienHe.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtLienHe.PlaceholderText = "Nhập";
            this.txtLienHe.ReadOnly = true;
            this.txtLienHe.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtLienHe.SelectedText = "";
            this.txtLienHe.SelectionLength = 0;
            this.txtLienHe.SelectionStart = 0;
            this.txtLienHe.ShortcutsEnabled = true;
            this.txtLienHe.Size = new System.Drawing.Size(272, 39);
            this.txtLienHe.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtLienHe.TabIndex = 21;
            this.txtLienHe.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtLienHe.TextMarginBottom = 0;
            this.txtLienHe.TextMarginLeft = 3;
            this.txtLienHe.TextMarginTop = 1;
            this.txtLienHe.TextPlaceholder = "Nhập";
            this.txtLienHe.UseSystemPasswordChar = false;
            this.txtLienHe.WordWrap = true;
            // 
            // bunifuSeparator3
            // 
            this.bunifuSeparator3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator3.BackgroundImage")));
            this.bunifuSeparator3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator3.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator3.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator3.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator3.LineThickness = 1;
            this.bunifuSeparator3.Location = new System.Drawing.Point(18, 233);
            this.bunifuSeparator3.Margin = new System.Windows.Forms.Padding(9, 14, 9, 14);
            this.bunifuSeparator3.Name = "bunifuSeparator3";
            this.bunifuSeparator3.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator3.Size = new System.Drawing.Size(790, 17);
            this.bunifuSeparator3.TabIndex = 10;
            // 
            // bunifuSeparator2
            // 
            this.bunifuSeparator2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator2.BackgroundImage")));
            this.bunifuSeparator2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator2.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator2.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator2.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator2.LineThickness = 1;
            this.bunifuSeparator2.Location = new System.Drawing.Point(18, 583);
            this.bunifuSeparator2.Margin = new System.Windows.Forms.Padding(6, 8, 6, 8);
            this.bunifuSeparator2.Name = "bunifuSeparator2";
            this.bunifuSeparator2.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator2.Size = new System.Drawing.Size(790, 10);
            this.bunifuSeparator2.TabIndex = 10;
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 1;
            this.bunifuSeparator1.Location = new System.Drawing.Point(18, 71);
            this.bunifuSeparator1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(790, 24);
            this.bunifuSeparator1.TabIndex = 10;
            // 
            // dragMove
            // 
            this.dragMove.Fixed = true;
            this.dragMove.Horizontal = true;
            this.dragMove.TargetControl = this.panel1;
            this.dragMove.Vertical = true;
            // 
            // frmNhaSanXuat
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 22F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(826, 646);
            this.Controls.Add(this.btnDong);
            this.Controls.Add(this.btnXoa);
            this.Controls.Add(this.btnCapNhat);
            this.Controls.Add(this.btnThem);
            this.Controls.Add(this.dgvNhaSanXuat);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.txtTenNhaSanXuat);
            this.Controls.Add(this.txtKhuVuc);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.txtZipCode);
            this.Controls.Add(this.txtDiaChi);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.txtWebsite);
            this.Controls.Add(this.txtLienHe);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.bunifuSeparator3);
            this.Controls.Add(this.bunifuSeparator2);
            this.Controls.Add(this.bunifuSeparator1);
            this.Controls.Add(this.panel1);
            this.Font = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.Name = "frmNhaSanXuat";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Nhà sản xuất";
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNhaSanXuat)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox txtTenNhaSanXuat;
        private Bunifu.UI.WinForms.BunifuTextBox txtKhuVuc;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txtZipCode;
        private Bunifu.UI.WinForms.BunifuTextBox txtDiaChi;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox txtWebsite;
        private Bunifu.UI.WinForms.BunifuTextBox txtLienHe;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvNhaSanXuat;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCapNhat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThem;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXoa;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDong;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator3;
        private Bunifu.Framework.UI.BunifuDragControl dragMove;
    }
}